package genkitruntime

import (
	"encoding/json"
	"fmt"
	"os"
	"testing"

	"github.com/full-chaos/dev-health-acr/internal/contextfabric/interpretprompt"
)

func servedInterpretationOutputSchema(t *testing.T) string {
	t.Helper()
	raw, err := InterpretationOutputSchema()
	if err != nil {
		t.Fatal(err)
	}
	var schema map[string]any
	if err := json.Unmarshal(raw, &schema); err != nil {
		t.Fatal(err)
	}
	schema["$id"] = interpretprompt.OutputSchemaID
	schema["title"] = interpretprompt.OutputSchemaTitle
	out, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	return string(out)
}

// ACR_REGEN_OUTPUT_SCHEMA=1 go test ./internal/contextfabric/genkitruntime -run TestServedInterpretationOutputSchema
// rewrites the generated file.
func TestServedInterpretationOutputSchemaEqualsTheRuntimeSchema(t *testing.T) {
	want := servedInterpretationOutputSchema(t)
	if os.Getenv("ACR_REGEN_OUTPUT_SCHEMA") == "1" {
		src := fmt.Sprintf("package interpretprompt\n\n// Code generated by genkitruntime's output schema parity test. DO NOT EDIT.\n\nconst outputSchemaJSON = %q\n", want)
		if err := os.WriteFile("../interpretprompt/zz_output_schema.go", []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	if interpretprompt.OutputSchema() != want {
		t.Fatal("interpretprompt.OutputSchema() is stale against InterpretationOutputSchema(): regenerate with ACR_REGEN_OUTPUT_SCHEMA=1")
	}
}
