package genkitruntime

import (
	"encoding/json"
	"fmt"
	"os"
	"testing"

	"github.com/full-chaos/dev-health-acr/internal/contextfabric/synthesisprompt"
)

func servedSynthesisOutputSchema(t *testing.T) string {
	t.Helper()
	raw, err := SynthesisOutputSchema()
	if err != nil {
		t.Fatal(err)
	}
	var schema map[string]any
	if err := json.Unmarshal(raw, &schema); err != nil {
		t.Fatal(err)
	}
	schema["$id"] = synthesisprompt.OutputSchemaID
	schema["title"] = synthesisprompt.OutputSchemaTitle
	out, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	return string(out)
}

// ACR_REGEN_OUTPUT_SCHEMA=1 go test ./internal/contextfabric/genkitruntime -run TestServedSynthesisOutputSchema
// rewrites the generated file.
func TestServedSynthesisOutputSchemaEqualsTheRuntimeSchema(t *testing.T) {
	want := servedSynthesisOutputSchema(t)
	if os.Getenv("ACR_REGEN_OUTPUT_SCHEMA") == "1" {
		src := fmt.Sprintf("package synthesisprompt\n\n// Code generated by genkitruntime's output schema parity test. DO NOT EDIT.\n\nconst outputSchemaJSON = %q\n", want)
		if err := os.WriteFile("../synthesisprompt/zz_output_schema.go", []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	if synthesisprompt.OutputSchema() != want {
		t.Fatal("synthesisprompt.OutputSchema() is stale against SynthesisOutputSchema(): regenerate with ACR_REGEN_OUTPUT_SCHEMA=1")
	}
}
