#!/usr/bin/env python3
"""ONE ingestion boundary. Nothing downstream ever sees an unvalidated value.

Four review rounds closed one fail-open path at a time and a fifth opened each time,
because the code trusted whatever shape reached it: a declared expectation could be a
list, an anchor could be missing a key, an attempt's `result` could be an integer. The
class was never "this predicate is wrong" -- it was "there is no boundary".

Everything enters through here. A corpus row that does not satisfy the schema is
`invalid_expectation` and is never scored; an attempt artefact that does not satisfy the
schema is `unparseable` and is never read as evidence. Neither is guessed at, and neither
reaches the scorer or the identity check in a half-trusted state.
"""

EXPECT_VALUES = {"serve", "refuse", "decline", "clarify"}

_SCHEMA = None
# bool is an int subclass in Python, so a JSON `true` satisfies BOTH `int` and `number`
# unless both are guarded. r10 found the hole in `number` because the guard had been written
# for `int` only -- one type at a time, which is the same shape as the boundary defect it
# sat next to. Numeric types are named ONCE here and guarded together.
_NUMERIC = {"int", "number"}
_TYPES = {"int": int, "number": (int, float), "string": str, "bool": bool,
          "object": dict, "array": list}


def schema():
    """The MEASURED artefact schema, loaded once from its data file.

    Generated by measure_schema.py from every path at every depth of the real artefacts.
    Not hand-written: see that file for why three review rounds could not fix this by
    hand.
    """
    global _SCHEMA
    if _SCHEMA is None:
        import json
        from pathlib import Path
        doc = json.loads((Path(__file__).parent / "artefact_schema.json").read_text())
        _SCHEMA = doc["nodes"]
    return _SCHEMA


def _type_ok(val, want, rule_type, nullable):
    """(ok, reason_fragment). None is admitted only where the schema says so."""
    if val is None:
        return (True, None) if nullable else (False, "is explicitly null; omit it instead")
    if rule_type in _NUMERIC and isinstance(val, bool):
        return False, f"must be {rule_type}, got bool"
    if not isinstance(val, want):
        return False, f"must be {rule_type}, got {type(val).__name__}"
    return True, None


def _check_node(node, node_name, path="attempt"):
    """Recursive shape check against the MEASURED schema. Returns a reason, or None.

    Every node the generator found is walked, to whatever depth it was found at. There is
    no list of "paths we remembered to type": a path the engine emits is in the schema
    because the schema is a report about what the engine emits.
    """
    spec = schema().get(node_name)
    if spec is None or not isinstance(node, dict):
        return None
    for key, rule in spec.items():
        if key not in node:
            if rule.get("required"):
                return f"{path}.{key} is required and absent"
            continue
        val = node[key]
        rule_type = rule.get("type")
        if rule_type is None:                 # measured as polymorphic: deliberately unchecked
            continue
        ok, why = _type_ok(val, _TYPES[rule_type], rule_type, rule.get("nullable"))
        if not ok:
            return f"{path}.{key} {why}"
        if val is None:
            continue
        if rule_type == "array":
            item_type = rule.get("items")
            if item_type:
                item_want = _TYPES[item_type]
                for i, item in enumerate(val):
                    ok, why = _type_ok(item, item_want, item_type,
                                       rule.get("items_nullable"))
                    if not ok:
                        return f"{path}.{key}[{i}] {why}"
                    if item is None:
                        continue
                    child = rule.get("element_node")
                    if child:
                        deeper = _check_node(item, child, f"{path}.{key}[{i}]")
                        if deeper:
                            return deeper
        elif rule_type == "object":
            child = rule.get("node")
            if child:
                deeper = _check_node(val, child, f"{path}.{key}")
                if deeper:
                    return deeper
    return None


def validate_corpus_row(row):
    """(ok, reason). Checks the DECLARED fields only; the rest of the row is the
    corpus's business."""
    if not isinstance(row, dict):
        return False, "row is not a mapping"

    expect = row.get("expect")
    if expect is not None and (not isinstance(expect, str) or expect not in EXPECT_VALUES):
        return False, f"expect must be one of {sorted(EXPECT_VALUES)} or None, got {expect!r}"

    basis = row.get("basis")
    if basis is not None and not isinstance(basis, str):
        return False, f"basis must be a string or None, got {type(basis).__name__}"

    anchor = row.get("anchor")
    if anchor is not None:
        if not isinstance(anchor, dict):
            return False, f"anchor must be a mapping or None, got {type(anchor).__name__}"
        for key in ("kind", "label"):
            if not isinstance(anchor.get(key), str) or not anchor.get(key):
                return False, f"anchor.{key} must be a non-empty string"

    nonexistent = row.get("nonexistent", False)
    # bool only: "false" is a string and would be truthy, which is how a declaration
    # meaning the opposite of what it says gets believed.
    if not isinstance(nonexistent, bool):
        return False, f"nonexistent must be a bool, got {type(nonexistent).__name__}"

    return True, None


def validate_attempt(attempt):
    """(ok, reason). An attempt envelope -- from an artefact file OR a live response.

    DEEP, and deliberately so. A shallow check passed `{"response": {"result": [1]}}`
    because `response` was a mapping, and the list then crashed whatever dereferenced it.
    An EMPTY result or failure mapping is VALID: an empty document is still a document,
    and rejecting it conflated "nothing in it" with "not readable".
    `status` must be an int; None and bool are rejected -- bool is an int subclass in
    Python, so `True` would otherwise pass as a status code.
    """
    if not isinstance(attempt, dict):
        return False, f"attempt is not a mapping, got {type(attempt).__name__}"

    reason = _check_node(attempt, "attempt")
    if reason:
        return False, reason
    return True, None


def load_attempt(path):
    """THE loader. The ONLY place an attempt artefact's JSON is decoded.

    Returns (ok, attempt, reason). Every consumer -- identity, the failure scanner, the
    shard writer -- goes through here, so none of them can hold a different opinion about
    whether a file is readable, and none of them can dereference an unvalidated shape.
    Four separate crashes came from four separate readers each decoding and trusting the
    same file in its own way.
    """
    import json
    try:
        with open(path) as fh:
            data = json.load(fh)
    except Exception as exc:                      # unreadable bytes, bad JSON, missing file
        return False, None, f"{type(exc).__name__}: {exc}"
    ok, reason = validate_attempt(data)
    if not ok:
        return False, None, reason
    return True, data, None
