package mcpclientfixtures

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// docPaths lists every Markdown guide under docs/examples/mcp-clients/
// this test suite covers, relative to the repository root.
var docPaths = []string{
	"docs/examples/mcp-clients/README.md",
	"docs/examples/mcp-clients/claude-code.md",
	"docs/examples/mcp-clients/cursor.md",
	"docs/examples/mcp-clients/codex.md",
	"docs/examples/mcp-clients/generic-stdio.md",
	"docs/examples/mcp-clients/proxy-and-custom-ca.md",
}

func readDoc(t *testing.T, root, relPath string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(root, relPath))
	if err != nil {
		t.Fatal(err)
	}
	return data
}

// TestInstallSidecarSnippetIsCanonicalEverywhere is the marker-based
// canonical-parity check for the "install the sidecar" setup step: every
// guide that embeds an "<!-- FIXTURE:install-sidecar -->" marked block
// must contain byte-for-byte the same text InstallSidecarSnippet
// generates, so a stale hand-edit (a changed command, a dropped warning,
// a swapped env var) in any one guide fails this test immediately rather
// than silently drifting from the others.
func TestInstallSidecarSnippetIsCanonicalEverywhere(t *testing.T) {
	root := findRepoRoot(t)
	want := strings.TrimRight(InstallSidecarSnippet, "\n")
	for _, relPath := range docPaths {
		data := readDoc(t, root, relPath)
		if !strings.Contains(string(data), "<!-- FIXTURE:install-sidecar -->") {
			continue
		}
		t.Run(relPath, func(t *testing.T) {
			got, err := ExtractMarkedBlock(data, "install-sidecar")
			if err != nil {
				t.Fatal(err)
			}
			if got != want {
				t.Fatalf("%s's install-sidecar block has drifted from InstallSidecarSnippet", relPath)
			}
		})
	}
}

// TestMarkedJSONAndTOMLSnippetsAreCanonical is the marker-based canonical-
// parity check for every standalone JSON/TOML fenced snippet across the
// per-client guides: each one is generated by exactly one Render*
// function in canonical.go/doc_variants.go, so a hand-edit that
// introduces a typo'd key, a stale command, or a dropped env var fails
// here instead of only being caught (or missed) by eye.
func TestMarkedJSONAndTOMLSnippetsAreCanonical(t *testing.T) {
	root := findRepoRoot(t)
	cases := []struct {
		relPath string
		marker  string
		render  func() string
	}{
		{"docs/examples/mcp-clients/claude-code.md", "claude-code-project-json", RenderClaudeCodeJSON},
		{"docs/examples/mcp-clients/claude-code.md", "claude-code-userscope-json", RenderClaudeCodeUserScopeJSON},
		{"docs/examples/mcp-clients/claude-code.md", "claude-code-fullexample-json", RenderClaudeCodeFullExampleJSON},
		{"docs/examples/mcp-clients/cursor.md", "cursor-project-json", RenderCursorJSON},
		{"docs/examples/mcp-clients/cursor.md", "cursor-fullexample-json", RenderCursorFullExampleJSON},
		{"docs/examples/mcp-clients/codex.md", "codex-doc-snippet-toml", RenderCodexTOMLDocSnippet},
		{"docs/examples/mcp-clients/codex.md", "codex-fullexample-toml", RenderCodexTOMLFullExample},
	}
	for _, tc := range cases {
		t.Run(tc.relPath+"/"+tc.marker, func(t *testing.T) {
			data := readDoc(t, root, tc.relPath)
			got, err := ExtractMarkedBlock(data, tc.marker)
			if err != nil {
				t.Fatal(err)
			}
			want := strings.TrimRight(tc.render(), "\n")
			if got != want {
				t.Fatalf("marker %q in %s has drifted from its canonical render", tc.marker, tc.relPath)
			}
		})
	}
}

// TestCursorSetupStepHeredocMatchesCanonicalModel proves cursor.md's
// "Create the config directory and file" heredoc -- not a standalone
// fence, so it cannot carry an HTML comment marker without breaking the
// heredoc's own content -- still matches RenderCursorSetupStepJSON()
// structurally via heredoc extraction rather than an eyeballed read.
func TestCursorSetupStepHeredocMatchesCanonicalModel(t *testing.T) {
	root := findRepoRoot(t)
	data := readDoc(t, root, "docs/examples/mcp-clients/cursor.md")
	var heredocJSON string
	for _, block := range ExtractFencedBlocks(data, "bash") {
		for _, doc := range ExtractHeredocBlocks(block, "EOF") {
			if strings.Contains(doc, `"mcpServers"`) {
				heredocJSON = doc
			}
		}
	}
	if heredocJSON == "" {
		t.Fatal("expected to find a heredoc-embedded mcpServers JSON block in cursor.md")
	}
	if want := strings.TrimRight(RenderCursorSetupStepJSON(), "\n"); heredocJSON != want {
		t.Fatal("cursor.md's setup-step heredoc JSON has drifted from RenderCursorSetupStepJSON()")
	}
}

// TestClaudeCodeAddJSONCLIReferenceStaysValidAndServeOnly checks the one
// snippet that is deliberately not canonical-parity-tested byte-for-byte:
// claude-code.md's `claude mcp add-json` CLI reference is an
// intentionally minimal, compact-JSON illustration of the CLI's own
// argument syntax, not a complete working config. It still must stay
// valid JSON and invoke exactly `acr-mcp serve`.
func TestClaudeCodeAddJSONCLIReferenceStaysValidAndServeOnly(t *testing.T) {
	root := findRepoRoot(t)
	data := readDoc(t, root, "docs/examples/mcp-clients/claude-code.md")
	const marker = "add-json acr '"
	var blob string
	for _, block := range ExtractFencedBlocks(data, "bash") {
		idx := strings.Index(block, marker)
		if idx < 0 {
			continue
		}
		rest := block[idx+len(marker):]
		if end := strings.Index(rest, "'"); end >= 0 {
			blob = rest[:end]
		}
	}
	if blob == "" {
		t.Fatal("expected to find the add-json CLI reference JSON blob")
	}
	var entry struct {
		Command string   `json:"command"`
		Args    []string `json:"args"`
	}
	if err := json.Unmarshal([]byte(blob), &entry); err != nil {
		t.Fatalf("add-json blob is not valid JSON: %v", err)
	}
	if !strings.HasSuffix(entry.Command, "acr-mcp") {
		t.Fatalf("expected command to end in acr-mcp, got %q", entry.Command)
	}
	if len(entry.Args) != 1 || entry.Args[0] != ServeArg {
		t.Fatalf("expected args [%q], got %#v", ServeArg, entry.Args)
	}
}

// TestEveryDocOnlyReferencesRealACRMCPSubcommands scans every fenced bash
// block in every guide for a literal "acr-mcp <word>" invocation and
// fails if the captured word is not one cmd/acr-mcp/main.go's switch
// actually dispatches on -- the direct enforcement of "a stale command
// snippet fails tests."
func TestEveryDocOnlyReferencesRealACRMCPSubcommands(t *testing.T) {
	root := findRepoRoot(t)
	for _, relPath := range docPaths {
		t.Run(relPath, func(t *testing.T) {
			data := readDoc(t, root, relPath)
			var allBash strings.Builder
			for _, block := range ExtractFencedBlocks(data, "bash") {
				allBash.WriteString(block)
				allBash.WriteString("\n")
			}
			invocations := ExtractACRMCPInvocations(allBash.String())
			if len(invocations) == 0 {
				t.Skip("no acr-mcp invocations in this doc's bash blocks")
			}
			for _, invocation := range invocations {
				if !KnownACRMCPSubcommands[invocation] {
					t.Fatalf("%s references unknown acr-mcp subcommand %q", relPath, invocation)
				}
			}
		})
	}
}

// TestDoctorGateNoteIsCanonicalEverywhere is the marker-based canonical-
// parity check for the doctor-behavior clause every guide's
// ACR_ENABLE_WRITEBACK bullet ends with: it must match DoctorGateNote
// byte-for-byte in every guide, so a future change to
// cmd/acr-mcp/main.go's root CLI dispatch (plain doctor live-by-default
// once static config is valid, --offline forced network-free, --live as a
// compatible explicit alias) that isn't also reflected here fails this
// test instead of leaving five guides quietly describing stale behavior.
func TestDoctorGateNoteIsCanonicalEverywhere(t *testing.T) {
	root := findRepoRoot(t)
	want := strings.TrimRight(DoctorGateNote, "\n")
	for _, relPath := range docPaths {
		data := readDoc(t, root, relPath)
		if !strings.Contains(string(data), "<!-- FIXTURE:doctor-gate-note -->") {
			continue
		}
		t.Run(relPath, func(t *testing.T) {
			got, err := ExtractMarkedBlock(data, "doctor-gate-note")
			if err != nil {
				t.Fatal(err)
			}
			if got != want {
				t.Fatalf("%s's doctor-gate-note clause has drifted from DoctorGateNote:\ngot:  %q\nwant: %q", relPath, got, want)
			}
		})
	}
}

// TestInstallSnippetChecksumContractMatchesReleasePolicy proves both
// canonical install snippets' consumer verification mechanism -- verify
// the signature over the *entire* SHA256SUMS manifest first, then select
// and verify only the single line matching the one archive actually
// downloaded, asserting exactly one such line exists -- has not drifted
// from docs/release-policy.md's own "Local publish contract" section,
// the authoritative source for this exact contract (see its "Consumers
// obtain signing/cosign.pub..." paragraph and the bash/powershell blocks
// immediately below it).
//
// The comparison is semantic (a shared checklist of structural tokens
// each side must contain), not a literal byte/line match, because the
// two documents legitimately differ in surface details that carry no
// contract meaning: release-policy.md illustrates with a concrete
// "acr-api_1.2.3_linux_amd64.tar.gz"-style example and single-quoted
// variable assignment, while the mcp-clients guides use an
// "acr-mcp_<version>_<os>_<arch>.tar.gz" placeholder and this package's
// existing double-quote convention. If docs/release-policy.md's own
// contract changes (a dropped assertion, a different flag, a switched
// tool), the elements list below stops matching release-policy.md
// itself, which fails this test just as loudly as a drifted snippet
// would.
//
// The POSIX line-selection element is deliberately NOT compared: this
// package's own InstallSidecarSnippet uses `awk -v name="$archive"
// '$2 == name'` (an exact-field match), while docs/release-policy.md's
// example still uses `grep -F "  $archive"` (a fixed-string, but not
// end-anchored, match) -- see
// TestInstallSidecarSnippetChecksumSelectionIsExactAgainstRealSBOMManifest
// for why `grep -F` alone matches a real archive's own
// "<archive>.spdx.json" SBOM sibling too and fails the "exactly one"
// assertion for every real release. This is a known, flagged-for-
// coordination gap in docs/release-policy.md's own example, not a drift
// in this package's snippet, so it is intentionally excluded from the
// shared-element checklist rather than forcing InstallSidecarSnippet
// back to the less precise `grep -F` selector to satisfy this test.
func TestInstallSnippetChecksumContractMatchesReleasePolicy(t *testing.T) {
	root := findRepoRoot(t)
	policyData := readDoc(t, root, "docs/release-policy.md")
	posixBlock := findFencedBlockContaining(t, policyData, "bash", "cosign verify-blob")
	psBlock := findFencedBlockContaining(t, policyData, "powershell", "verify-blob --key signing/cosign.pub")

	posixElements := []string{
		"cosign verify-blob",
		"--insecure-ignore-tlog SHA256SUMS",
		"= 1",
		"sha256sum --check -",
		"shasum -a 256 --check -",
	}
	assertSharedElements(t, "POSIX", posixBlock, InstallSidecarSnippet, posixElements)

	psElements := []string{
		"verify-blob --key signing/cosign.pub",
		"--insecure-ignore-tlog SHA256SUMS",
		"EndsWith",
		".Count -ne 1",
		"Get-FileHash",
	}
	assertSharedElements(t, "Windows", psBlock, InstallSidecarWindowsSnippet, psElements)
}

// findFencedBlockContaining locates the one fenced code block of the
// given language in data that contains needle, failing the test if none
// is found.
func findFencedBlockContaining(t *testing.T, data []byte, lang, needle string) string {
	t.Helper()
	for _, block := range ExtractFencedBlocks(data, lang) {
		if strings.Contains(block, needle) {
			return block
		}
	}
	t.Fatalf("expected to find a %s block containing %q in docs/release-policy.md", lang, needle)
	return ""
}

// assertSharedElements fails the test if any element is missing from
// either policyBlock (docs/release-policy.md's own authoritative text)
// or snippet (this package's canonical Go-rendered install text) --
// catching drift in either direction.
func assertSharedElements(t *testing.T, label, policyBlock, snippet string, elements []string) {
	t.Helper()
	for _, want := range elements {
		if !strings.Contains(policyBlock, want) {
			t.Fatalf("%s: docs/release-policy.md's own contract no longer contains %q -- update this test's element list to match its current contract", label, want)
		}
		if !strings.Contains(snippet, want) {
			t.Fatalf("%s: the canonical install snippet has drifted from docs/release-policy.md's contract: missing %q", label, want)
		}
	}
}
