package eventspec

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
)

// Generate derives every generated artefact from All, deterministically.
// It is called by cmd/gen (go:generate) to refresh the checked-in files and
// by regen_test.go to prove they are still byte-identical to the spec --
// the two callers must never diverge, or the pin would not be testing what
// production actually ships.
func Generate() (map[string][]byte, error) {
	goSrc, err := generateGo()
	if err != nil {
		return nil, fmt.Errorf("generate zz_generated.go: %w", err)
	}
	schema, err := generateSchema()
	if err != nil {
		return nil, fmt.Errorf("generate schema.json: %w", err)
	}
	return map[string][]byte{
		"zz_generated.go": goSrc,
		"schema.json":     schema,
	}, nil
}

func generateGo() ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/contextfabric/eventspec/cmd/gen from spec.go. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with: go generate ./internal/contextfabric/eventspec/...\n\n")
	b.WriteString("package eventspec\n\n")
	b.WriteString("// FieldKeys lists, in declaration order, every JSON key an event's variant\n")
	b.WriteString("// carries. It is the generated mirror of Event.Fields -- present so a\n")
	b.WriteString("// consumer can range over an event's shape without walking Field structs.\n")
	b.WriteString("func FieldKeys(e Event) []string {\n")
	b.WriteString("\tkeys := make([]string, 0, len(e.Fields))\n")
	b.WriteString("\tfor _, f := range e.Fields {\n")
	b.WriteString("\t\tkeys = append(keys, f.Key)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn keys\n")
	b.WriteString("}\n\n")

	b.WriteString("// ByID is the generated lookup from Event.ID to its declaration -- generated\n")
	b.WriteString("// rather than hand-maintained so it can never drift from All.\n")
	b.WriteString("var ByID = map[string]Event{\n")
	// stable order
	events := append([]Event{}, All...)
	sort.Slice(events, func(i, j int) bool { return events[i].ID < events[j].ID })
	for _, e := range events {
		fmt.Fprintf(&b, "\t%q: %s,\n", e.ID, goVarName(e))
	}
	b.WriteString("}\n")

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w (unformatted:\n%s)", err, b.String())
	}
	return out, nil
}

// goVarName maps an event's stable ID back to the exported var this package
// declares it under in spec.go. Both variables generation touches
// (RankedCutSummary, AnchorSlotDisplaced) are named here explicitly so a
// spec.go addition that forgets to extend this map fails generation loudly
// (KeyError on ByID build) rather than silently omitting the event.
func goVarName(e Event) string {
	switch e.ID {
	case RankedCutSummary.ID:
		return "RankedCutSummary"
	case AnchorSlotDisplaced.ID:
		return "AnchorSlotDisplaced"
	default:
		panic("eventspec: goVarName has no mapping for " + e.ID + " -- add one before regenerating")
	}
}

// jsonField mirrors Field for schema.json, so the schema's own shape is
// generated rather than hand-typed a second time.
type jsonField struct {
	Key              string      `json:"key"`
	Type             string      `json:"type"`
	Presence         string      `json:"presence"`
	ClosedVocabulary []string    `json:"closed_vocabulary,omitempty"`
	Applicability    string      `json:"applicability,omitempty"`
	Fields           []jsonField `json:"fields,omitempty"`
}

type jsonEvent struct {
	ID                 string      `json:"id"`
	Msg                string      `json:"msg"`
	Level              string      `json:"level"`
	Multiplicity       string      `json:"multiplicity"`
	Attribution        []string    `json:"attribution"`
	BoundedAggregation string      `json:"bounded_aggregation"`
	Fields             []jsonField `json:"fields"`
}

func toJSONFields(fs []Field) []jsonField {
	out := make([]jsonField, 0, len(fs))
	for _, f := range fs {
		out = append(out, jsonField{
			Key:              f.Key,
			Type:             string(f.Type),
			Presence:         string(f.Presence),
			ClosedVocabulary: f.ClosedVocabulary,
			Applicability:    f.Applicability,
			Fields:           toJSONFields(f.Fields),
		})
	}
	return out
}

func generateSchema() ([]byte, error) {
	events := append([]Event{}, All...)
	sort.Slice(events, func(i, j int) bool { return events[i].ID < events[j].ID })
	out := make([]jsonEvent, 0, len(events))
	for _, e := range events {
		out = append(out, jsonEvent{
			ID:                 e.ID,
			Msg:                e.Msg,
			Level:              string(e.Level),
			Multiplicity:       string(e.Multiplicity),
			Attribution:        e.Attribution,
			BoundedAggregation: e.BoundedAggregation,
			Fields:             toJSONFields(e.Fields),
		})
	}
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetIndent("", "  ")
	if err := enc.Encode(out); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}
