// Code generated by internal/contextfabric/eventspec/cmd/gen from spec.go. DO NOT EDIT.
// Regenerate with: go generate ./internal/contextfabric/eventspec/...

package eventspec

// FieldKeys lists, in declaration order, every JSON key an event's variant
// carries. It is the generated mirror of Event.Fields -- present so a
// consumer can range over an event's shape without walking Field structs.
func FieldKeys(e Event) []string {
	keys := make([]string, 0, len(e.Fields))
	for _, f := range e.Fields {
		keys = append(keys, f.Key)
	}
	return keys
}

// ByID is the generated lookup from Event.ID to its declaration -- generated
// rather than hand-maintained so it can never drift from All.
var ByID = map[string]Event{
	"graphrank.anchor_slot_displaced": AnchorSlotDisplaced,
	"graphrank.ranked_cut_summary":    RankedCutSummary,
}
