package falkorgraph

import (
	"testing"

	"github.com/full-chaos/dev-health-acr/internal/contextfabric"
	contractsv1 "github.com/full-chaos/dev-health-acr/internal/contracts/v1"
)

// This file is the CHAOS-3835 codex ROUND-2 review finding-2 proof (P2,
// id_only.go:150-152 in the round-1-fixed revision): the id-only decision
// inspected pipeline_name and branch only, but ciRunSearchText
// (search_text.go) also appends retrievalHandles(entity) -- the entity's
// aliases and previous names -- to the SAME composed text. A CI run with
// id-shaped pipeline_name/branch but a semantic alias ("nightly smoke") was
// skipped (and, post round-1, cleared) despite carrying real semantic
// content in the text it would otherwise have embedded.

func ciRunEntity(name, branch string, aliases, previousNames []string) contextfabric.EntityProjection {
	props := map[string]contextfabric.ScalarValue{}
	if name != "" {
		props["pipeline_name"] = scalar(name)
	}
	if branch != "" {
		props["branch"] = scalar(branch)
	}
	return contextfabric.EntityProjection{
		Subject:       contextfabric.SubjectRef{Kind: contractsv1.ContextFabricSubjectCIRun, CanonicalID: "ci_pipeline_run:x", Label: "CI run"},
		Properties:    props,
		Aliases:       aliases,
		PreviousNames: previousNames,
	}
}

// TestIsPureIdentifierCIRunEmbedsOnASemanticAliasEvenWithIDOnlyNameAndBranch
// is the finding-2 proof: id-shaped name/branch, but a semantic alias, must
// embed -- the row's composed search_text (via retrievalHandles) carries
// real content the old field-only check was blind to.
//
// Mutation check: reverting the id_only.go fix (dropping the handles check
// from isPureIdentifierCIRun) makes this test fail -- the row goes back to
// reading as id-only. Verified live against the round-1-only code.
func TestIsPureIdentifierCIRunEmbedsOnASemanticAliasEvenWithIDOnlyNameAndBranch(t *testing.T) {
	t.Parallel()
	entity := ciRunEntity("run-12345", "build-6789", []string{"nightly smoke"}, nil)
	if isPureIdentifierCIRun(entity) {
		t.Fatal("a CI run with a semantic alias must embed, even with id-shaped pipeline_name/branch (round-2 finding 2)")
	}
	if got := isPureIdentifierSubject(entity); got {
		t.Fatal("isPureIdentifierSubject must dispatch to the same (embed) verdict as isPureIdentifierCIRun")
	}
}

// TestIsPureIdentifierCIRunEmbedsOnASemanticPreviousNameEvenWithEmptyNameAndBranch
// covers the OTHER retrievalHandles source (PreviousNames, not just
// Aliases) with empty (not just id-shaped) name/branch -- the L5 degenerate
// case that must still embed once a semantic previous name is present.
func TestIsPureIdentifierCIRunEmbedsOnASemanticPreviousNameEvenWithEmptyNameAndBranch(t *testing.T) {
	t.Parallel()
	entity := ciRunEntity("", "", nil, []string{"fullstack-acceptance"})
	if isPureIdentifierCIRun(entity) {
		t.Fatal("a CI run with a semantic previous name must embed, even with empty pipeline_name/branch (round-2 finding 2)")
	}
}

// TestIsPureIdentifierCIRunStaysIDOnlyWhenHandlesAreThemselvesIDShaped is
// the negative control: id-shaped aliases/previous names (e.g. another
// autogenerated run handle) must NOT flip the verdict to embed -- only
// genuinely semantic handle content should.
func TestIsPureIdentifierCIRunStaysIDOnlyWhenHandlesAreThemselvesIDShaped(t *testing.T) {
	t.Parallel()
	entity := ciRunEntity("run-12345", "", []string{"build-6789"}, []string{"12345"})
	if !isPureIdentifierCIRun(entity) {
		t.Fatal("id-shaped aliases/previous names must not turn an otherwise id-only row into an embed -- only semantic handle content should")
	}
}

// TestIsPureIdentifierCIRunStaysIDOnlyWithNoHandlesAtAll pins the ordinary
// L5 degenerate case is unaffected: no aliases, no previous names, id-only
// (or empty) name/branch -- still id-only.
func TestIsPureIdentifierCIRunStaysIDOnlyWithNoHandlesAtAll(t *testing.T) {
	t.Parallel()
	entity := ciRunEntity("", "", nil, nil)
	if !isPureIdentifierCIRun(entity) {
		t.Fatal("the documented L5 degenerate case (no name, no branch, no handles) must remain id-only")
	}
}
