package falkorgraph

import (
	"regexp"
	"strings"

	"github.com/full-chaos/dev-health-acr/internal/contextfabric"
	contractsv1 "github.com/full-chaos/dev-health-acr/internal/contracts/v1"
)

// This file is the CHAOS-3835 (embed-text spec v2 §5 L5, §6.5 T5) id-only
// skip: a RECORD-level embed decision, distinct from embedKindSkipped's
// WHOLE-KIND decision (vector_projection.go). L5's measured target is the
// ci_pipeline_run kind -- 78% of the live corpus, degenerating to
// `CI run repo: X` for the 22% of rows with neither a pipeline_name nor a
// branch (see ciRunSearchText's own "L5/T5 skip-list" comment) -- so this
// is scoped to that kind today, at the SAME seam (collectEmbedTargets) the
// kind skip-list and MaxTextRunes gating already apply. Extending the skip
// to another kind is a template-shaped decision for that kind's own §2
// section, not a change to the general-purpose primitive below.

// idOnlyPureDigits matches a token that is NOTHING but Unicode decimal
// digits (Nd, which includes fullwidth digits, Arabic-indic digits, etc --
// deliberately not ASCII \d, since an id is exactly as "no semantic
// content" regardless of script).
var idOnlyPureDigits = regexp.MustCompile(`^\p{Nd}+$`)

// idOnlyLetterHyphenDigits matches a token shaped like an autogenerated
// id/build handle: a Unicode letter run, ONE separator (hyphen or
// underscore -- the ticket-key shape §2 already derives for work_item,
// `CHAOS-1725`, `ABC-1`, and the CI/build-tooling convention `run-12345`),
// then a digit run, and NOTHING else. A separator is REQUIRED -- letters
// touching digits with no separator (`log4j`, `s3`) stays real content, not
// an id, since every id shape the live corpus actually produces (ticket
// keys, build/run handles) uses one. Requiring the separator is the
// conservative direction: it can only make the detector skip LESS, never
// more, so the failure mode of an ambiguous token is "stays embedded",
// which is the fail-safe side (T5's directive: "implement conservative").
var idOnlyLetterHyphenDigits = regexp.MustCompile(`^\p{L}+[-_]\p{Nd}+$`)

// isPureIdentifierText reports whether text carries no letter-sequence
// beyond an identifier/number shape -- the general-purpose primitive T5's
// detector is built from (spec §5 L5: "text is (kind prefix +) id/number-
// only after normalization").
//
// Rule, exactly: trim the text; split on Unicode whitespace into tokens;
// text is pure-identifier iff EVERY token matches idOnlyPureDigits or
// idOnlyLetterHyphenDigits. A single token carrying any OTHER letter
// content -- a real word ("fix", "login", "smoke"), a slug that isn't
// id-shaped ("fullstack-acceptance", ends in letters not digits) -- means
// the text has semantic content, so the whole text is NOT pure-identifier.
//
// Empty text is explicitly NOT this function's concern and returns false:
// an empty field is a distinct, already-existing gating reason (collectEmbedTargets'
// add() drops empty text/canonicalID before any target is even considered), and
// this detector must never double-count that case under the id-only label
// -- the two reasons stay mutually exclusive by construction (spec §7 D2:
// the count must be distinguishable by reason).
func isPureIdentifierText(text string) bool {
	text = strings.TrimSpace(text)
	if text == "" {
		return false
	}
	for _, token := range strings.Fields(text) {
		if !idOnlyPureDigits.MatchString(token) && !idOnlyLetterHyphenDigits.MatchString(token) {
			return false
		}
	}
	return true
}

// isPureIdentifierCIRun reports whether a ci_pipeline_run row's own name
// fields carry no content beyond a bare identifier (spec §5 L5's literal
// criterion, extended one conservative step).
//
// The LITERAL L5 criterion is "rows whose composed text has no name/branch"
// -- 22% of the live corpus, matching ciRunSearchText's documented
// degenerate shape `CI run repo: X`. This function reads that same
// criterion off the SOURCE fields (pipeline_name, branch) rather than
// re-parsing the composed text, because the composed text also carries
// repo and the retrieval-handle line, which are structural context every
// CI row carries regardless of whether it has a name -- never part of
// L5's criterion, and parsing them back out of a flattened string is
// exactly the re-derivation hazard search_text.go's header warns against
// (the ONE place kind-specific field meaning is unambiguous is the entity
// struct the switch already dispatches on).
//
// It extends "empty" to "empty OR itself id-shaped" so a POPULATED but
// bare-identifier pipeline_name or branch (an autogenerated "run-12345", a
// raw build number) also counts: the row still carries no human-findable
// name for a semantic query to reach it by. repo and the run id are
// deliberately never examined here -- they are not name fields.
func isPureIdentifierCIRun(entity contextfabric.EntityProjection) bool {
	name := propText(entity, "pipeline_name")
	branch := propText(entity, "branch")
	nameIsIDOnly := name == "" || isPureIdentifierText(name)
	branchIsIDOnly := branch == "" || isPureIdentifierText(branch)
	return nameIsIDOnly && branchIsIDOnly
}

// isPureIdentifierSubject dispatches the per-kind id-only decision the same
// way subjectSearchText's switch dispatches per-kind composition -- the ONE
// place this decision is made, extensible to another kind exactly the way
// a new §2 template is added. Only ci_pipeline_run has a documented id-only
// population today (spec §1); every other kind returns false unconditionally
// rather than guessing at a criterion the spec never measured.
func isPureIdentifierSubject(entity contextfabric.EntityProjection) bool {
	switch entity.Subject.Kind {
	case contractsv1.ContextFabricSubjectCIRun:
		return isPureIdentifierCIRun(entity)
	default:
		return false
	}
}
