-- ACR operational state. Dev Health analytics evidence remains read-only in ClickHouse.
-- IDs are generated by the Go service; there are intentionally no cross-database
-- foreign keys to dev-health-ops organization or repository tables.

CREATE SCHEMA IF NOT EXISTS acr;

CREATE TABLE IF NOT EXISTS acr.client_credentials (
    credential_id TEXT PRIMARY KEY,
    org_id UUID NOT NULL,
    name TEXT NOT NULL,
    token_prefix TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    repository_scopes JSONB NOT NULL DEFAULT '[]'::jsonb,
    scopes JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_by TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    last_used_ip INET,
    last_used_user_agent TEXT,
    CHECK (token_prefix LIKE 'fcacr\_%'),
    CHECK (jsonb_typeof(repository_scopes) = 'array'),
    CHECK (jsonb_typeof(scopes) = 'array')
);

CREATE INDEX IF NOT EXISTS ix_acr_client_credentials_org_active
    ON acr.client_credentials (org_id, revoked_at, expires_at);

CREATE TABLE IF NOT EXISTS acr.context_packet_snapshots (
    context_packet_id TEXT PRIMARY KEY,
    org_id UUID NOT NULL,
    repo_id UUID NOT NULL,
    repo_slug TEXT NOT NULL,
    request_id TEXT NOT NULL,
    schema_version TEXT NOT NULL,
    query_version TEXT NOT NULL,
    ranking_version TEXT NOT NULL,
    scope_resolution TEXT NOT NULL,
    status TEXT NOT NULL,
    payload JSONB NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CHECK (schema_version = 'context_packet.v1'),
    CHECK (scope_resolution IN ('exact_commit', 'branch_filtered', 'repo_fallback', 'unresolved')),
    CHECK (status IN ('complete', 'partial', 'degraded', 'empty'))
);

CREATE INDEX IF NOT EXISTS ix_acr_packet_snapshots_org_repo_generated
    ON acr.context_packet_snapshots (org_id, repo_id, generated_at DESC);
CREATE INDEX IF NOT EXISTS ix_acr_packet_snapshots_expiry
    ON acr.context_packet_snapshots (expires_at);

CREATE TABLE IF NOT EXISTS acr.agent_episodes (
    episode_id TEXT PRIMARY KEY,
    org_id UUID NOT NULL,
    repo_id UUID NOT NULL,
    repo_slug TEXT NOT NULL,
    context_packet_id TEXT NOT NULL,
    client_episode_id TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    schema_version TEXT NOT NULL,
    outcome TEXT NOT NULL,
    retention_class TEXT NOT NULL,
    redaction_state TEXT NOT NULL DEFAULT 'active',
    payload JSONB NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,
    redacted_at TIMESTAMPTZ,
    CHECK (schema_version = 'agent_episode.v1'),
    CHECK (outcome IN ('succeeded', 'failed', 'abandoned', 'superseded', 'unknown')),
    CHECK (retention_class IN ('default_90d', 'short_30d', 'legal_hold', 'no_persist')),
    CHECK (redaction_state IN ('active', 'redacted', 'purged_tombstone')),
    CHECK (ended_at >= started_at),
    UNIQUE (org_id, idempotency_key),
    UNIQUE (org_id, client_episode_id)
);

CREATE INDEX IF NOT EXISTS ix_acr_agent_episodes_org_repo_created
    ON acr.agent_episodes (org_id, repo_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_acr_agent_episodes_packet
    ON acr.agent_episodes (org_id, context_packet_id);
CREATE INDEX IF NOT EXISTS ix_acr_agent_episodes_expiry
    ON acr.agent_episodes (expires_at)
    WHERE retention_class <> 'legal_hold';

CREATE TABLE IF NOT EXISTS acr.audit_events (
    audit_event_id UUID PRIMARY KEY,
    org_id UUID NOT NULL,
    repo_id UUID,
    actor_type TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    status TEXT NOT NULL,
    request_id TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    CHECK (status IN ('success', 'failure', 'denied'))
);

CREATE INDEX IF NOT EXISTS ix_acr_audit_events_org_created
    ON acr.audit_events (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_acr_audit_events_resource
    ON acr.audit_events (org_id, resource_type, resource_id, created_at DESC);

COMMENT ON COLUMN acr.client_credentials.token_hash IS
    'One-way hash of a high-entropy fcacr_ bearer. Plaintext is shown only once and never persisted.';
COMMENT ON COLUMN acr.context_packet_snapshots.payload IS
    'Immutable validated context_packet.v1 snapshot. Default retention is 30 days.';
COMMENT ON COLUMN acr.agent_episodes.payload IS
    'Validated sanitized agent_episode.v1 payload. Raw transcripts are not accepted in SVS.';
