package directread

// GraphQL root-field policy of graphql_query (CHAOS-7036 design D.8, form
// iii; slice S1b, CHAOS-7075).
//
// ONE fact, no second list: the policy of a root field is DERIVED at load
// from the run_operation catalogue (operations.v1.json, generated by
// cmd/operationpolicy). Every served operation's registered document has
// exactly one root field whose arguments are either bound to a document
// variable (`filter: $filter`) or a constant literal (`dimension: REPO`).
// So for a free query:
//
//   - the allowed root fields are the root fields of the served operations;
//   - an argument bound to $v is checked as the variable v of that
//     operation (the same VariableRule tree, forced scope, constraints,
//     acr-set values and cost clamps run_operation uses);
//   - a literal argument is fixed: a client value must equal it;
//   - the allowed selection is that operation's output allowlist;
//   - the caller-class rule and the row id paths are that operation's.
//
// Two root fields are served by two operations each (catalog:
// catalogValues and acrRepositoryScopes; analytics: investmentBreakdown and
// investmentFull). Their candidates are ordered STRICTEST FIRST (lead ruling
// R2): an operation refused to a restricted caller before one served to it,
// then the narrower output allowlist, then more fixed literal arguments,
// then the name. A free query maps to the first candidate that admits it,
// so an ambiguous shape always maps to the stricter operation.
//
// The derived allowlist is also written, by cmd/operationpolicy, to
// contracts/mcp/graphql_roots.v1.json (RootsFileJSON), the list GWC's MCP
// listener (CHAOS-7085) must admit: acr's roots must be a subset of it.

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"sync"

	"github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// GraphQLRootsContract is the contract name of graphql_roots.v1.json.
const GraphQLRootsContract = "acr.mcp.graphql_roots.v1"

// OpsSchemaContract is the contract name of the embedded SDL wrapper.
const OpsSchemaContract = "acr.mcp.ops_schema.v1"

// The embedded ops SDL: a JSON wrapper (ops_schema.v1.json, written by
// cmd/operationpolicy) around a byte-identical copy of
// contracts/mcp/ops-catalogue/schema.graphql. JSON, because the container
// build context admits only .go and .json under internal/.
//
//go:embed ops_schema.v1.json
var embeddedOpsSchemaFile []byte

// OpsSchemaFile is the wire shape of ops_schema.v1.json.
type OpsSchemaFile struct {
	Contract     string `json:"contract"`
	Source       string `json:"source"`
	SchemaDigest string `json:"schema_digest"`
	SDL          string `json:"sdl"`
}

// EncodeOpsSchemaFile renders ops_schema.v1.json for an SDL.
func EncodeOpsSchemaFile(sdl []byte, source string) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	err := enc.Encode(OpsSchemaFile{Contract: OpsSchemaContract, Source: source, SchemaDigest: SchemaDigestOf(sdl), SDL: string(sdl)})
	return buf.Bytes(), err
}

// EmbeddedOpsSchema returns a copy of the embedded ops SDL bytes. A wrapper
// that does not decode, names another contract or whose digest does not
// recompute yields nil, and every derivation over it fails closed.
func EmbeddedOpsSchema() []byte {
	var file OpsSchemaFile
	dec := json.NewDecoder(bytes.NewReader(embeddedOpsSchemaFile))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&file); err != nil || file.Contract != OpsSchemaContract || SchemaDigestOf([]byte(file.SDL)) != file.SchemaDigest {
		return nil
	}
	return []byte(file.SDL)
}

// GraphQLLimits are the query caps acr applies before the wire. GWC's MCP
// listener (CHAOS-7085) has its own caps (depth 10, aliases 15, complexity
// 150 in gqlgen's default metric: one per selected field); acr's are at
// least as strict, so acr refuses first whatever the listener would refuse.
type GraphQLLimits struct {
	// MaxQueryBytes bounds the query text.
	MaxQueryBytes int `json:"max_query_bytes"`
	// MaxDepth bounds the selection depth; a root field is depth 1.
	MaxDepth int `json:"max_depth"`
	// MaxAliases bounds aliases (allowed on root fields only).
	MaxAliases int `json:"max_aliases"`
	// MaxRootFields bounds the root selections of one query.
	MaxRootFields int `json:"max_root_fields"`
	// MaxFields bounds every selected field, __typename included, counted
	// on the client query AND on the query acr sends (after the row id
	// add). It stays at or below the listener's complexity cap.
	MaxFields int `json:"max_fields"`
	// MaxComplexity bounds the sum of the root fields' cost weights.
	MaxComplexity int `json:"max_complexity"`
	// MaxComputeRoots bounds root fields of the compute cost class.
	MaxComputeRoots int `json:"max_compute_roots"`
}

// DefaultGraphQLLimits are acr's caps, each at or below the MCP listener's
// (CHAOS-7085: depth 10, aliases 15, complexity 150).
func DefaultGraphQLLimits() GraphQLLimits {
	return GraphQLLimits{
		MaxQueryBytes:   8 * 1024,
		MaxDepth:        10,
		MaxAliases:      5,
		MaxRootFields:   5,
		MaxFields:       150,
		MaxComplexity:   10,
		MaxComputeRoots: 1,
	}
}

// GraphQLCostWeight is the complexity weight of one root field of a cost
// class (design D.6 classes).
func GraphQLCostWeight(class CostClass) int {
	switch class {
	case CostCatalog:
		return 1
	case CostList, CostSeries:
		return 2
	case CostAnalyticsBatch:
		return 4
	case CostCompute:
		return 10
	default:
		return 10
	}
}

// rootCandidate is one served operation behind a root field.
type rootCandidate struct {
	op *OperationPolicy
	// bindings maps an argument name to the document variable it binds.
	bindings map[string]string
	// literals maps an argument name to its fixed document value.
	literals map[string]*ast.Value
	// literalJSON is literals decoded to the variable-tree form.
	literalJSON map[string]any
	// varTypes maps a document variable to its SDL type text.
	varTypes map[string]string
}

// GraphQLRootPolicy is the derived policy of one allowed root field.
type GraphQLRootPolicy struct {
	Field      string
	candidates []*rootCandidate
}

// Operations lists the candidate operation names, strictest first.
func (r *GraphQLRootPolicy) Operations() []string {
	out := make([]string, len(r.candidates))
	for i, c := range r.candidates {
		out[i] = c.op.Name
	}
	return out
}

// CostClass is the root's cost class: the heaviest candidate's.
func (r *GraphQLRootPolicy) CostClass() CostClass {
	class := r.candidates[0].op.CostClass
	for _, c := range r.candidates[1:] {
		if GraphQLCostWeight(c.op.CostClass) > GraphQLCostWeight(class) {
			class = c.op.CostClass
		}
	}
	return class
}

// GraphQLPolicy is the loaded root-field policy.
type GraphQLPolicy struct {
	catalogue *Catalogue
	schema    *ast.Schema
	roots     map[string]*GraphQLRootPolicy
	limits    GraphQLLimits
}

var (
	defaultGraphQLPolicyOnce sync.Once
	defaultGraphQLPolicy     *GraphQLPolicy
	defaultGraphQLPolicyErr  error
)

// DefaultGraphQLPolicy derives the policy from the embedded catalogue and
// the embedded SDL, once.
func DefaultGraphQLPolicy() (*GraphQLPolicy, error) {
	defaultGraphQLPolicyOnce.Do(func() {
		cat, err := DefaultCatalogue()
		if err != nil {
			defaultGraphQLPolicyErr = err
			return
		}
		defaultGraphQLPolicy, defaultGraphQLPolicyErr = NewGraphQLPolicy(cat, EmbeddedOpsSchema(), DefaultGraphQLLimits())
	})
	return defaultGraphQLPolicy, defaultGraphQLPolicyErr
}

// ErrGraphQLPolicyInvalid wraps every derivation failure.
var ErrGraphQLPolicyInvalid = errors.New("graphql root policy invalid")

func policyErr(format string, args ...any) error {
	return fmt.Errorf("%w: %s", ErrGraphQLPolicyInvalid, fmt.Sprintf(format, args...))
}

// NewGraphQLPolicy derives the root-field policy. It is fail closed: the
// SDL must be the one the catalogue was generated from, and every served
// document must be one root field with top-level variable or constant
// arguments and no nested argument, fragment or directive.
func NewGraphQLPolicy(cat *Catalogue, sdl []byte, limits GraphQLLimits) (*GraphQLPolicy, error) {
	if cat == nil {
		return nil, policyErr("no catalogue")
	}
	if got := SchemaDigestOf(sdl); got != cat.SchemaDigest() {
		return nil, policyErr("SDL digest %s, catalogue generated against %s", got, cat.SchemaDigest())
	}
	if limits.MaxQueryBytes <= 0 || limits.MaxDepth <= 0 || limits.MaxAliases < 0 || limits.MaxRootFields <= 0 ||
		limits.MaxFields <= 0 || limits.MaxComplexity <= 0 || limits.MaxComputeRoots < 0 {
		return nil, policyErr("limits must be positive")
	}
	schema, err := gqlparser.LoadSchema(&ast.Source{Name: "ops schema", Input: string(sdl)})
	if err != nil {
		return nil, policyErr("SDL does not load: %v", err)
	}
	if schema.Query == nil {
		return nil, policyErr("SDL has no Query type")
	}
	p := &GraphQLPolicy{catalogue: cat, schema: schema, roots: map[string]*GraphQLRootPolicy{}, limits: limits}
	for i := range cat.file.Operations {
		op := &cat.file.Operations[i]
		cand, field, err := deriveCandidate(schema, op)
		if err != nil {
			return nil, policyErr("operation %q: %v", op.Name, err)
		}
		root := p.roots[field]
		if root == nil {
			root = &GraphQLRootPolicy{Field: field}
			p.roots[field] = root
		}
		root.candidates = append(root.candidates, cand)
	}
	for _, root := range p.roots {
		sort.SliceStable(root.candidates, func(i, j int) bool { return candidateStricter(root.candidates[i], root.candidates[j]) })
	}
	return p, nil
}

// candidateStricter is the R2 order: a is tried before b.
func candidateStricter(a, b *rootCandidate) bool {
	ar, br := a.op.Scope(CallerRestricted).Served, b.op.Scope(CallerRestricted).Served
	if ar != br {
		return !ar
	}
	if len(a.op.Outputs) != len(b.op.Outputs) {
		return len(a.op.Outputs) < len(b.op.Outputs)
	}
	if len(a.literals) != len(b.literals) {
		return len(a.literals) > len(b.literals)
	}
	return a.op.Name < b.op.Name
}

func deriveCandidate(schema *ast.Schema, op *OperationPolicy) (*rootCandidate, string, error) {
	doc, errs := gqlparser.LoadQuery(schema, op.DocumentText)
	if len(errs) > 0 {
		return nil, "", fmt.Errorf("document does not validate against the SDL: %v", errs)
	}
	if len(doc.Operations) != 1 || len(doc.Fragments) != 0 {
		return nil, "", errors.New("document must be one operation with no fragment")
	}
	def := doc.Operations[0]
	if def.Operation != ast.Query || len(def.Directives) != 0 {
		return nil, "", errors.New("document must be a query with no directive")
	}
	if len(def.SelectionSet) != 1 {
		return nil, "", errors.New("document must select exactly one root field")
	}
	field, ok := def.SelectionSet[0].(*ast.Field)
	if !ok || field.Alias != field.Name || len(field.Directives) != 0 {
		return nil, "", errors.New("root selection must be one unaliased field with no directive")
	}
	if err := noNestedArguments(field.SelectionSet); err != nil {
		return nil, "", err
	}
	cand := &rootCandidate{
		op:          op,
		bindings:    map[string]string{},
		literals:    map[string]*ast.Value{},
		literalJSON: map[string]any{},
		varTypes:    map[string]string{},
	}
	for _, v := range def.VariableDefinitions {
		cand.varTypes[v.Variable] = v.Type.String()
	}
	bound := map[string]bool{}
	for _, arg := range field.Arguments {
		if arg.Value.Kind == ast.Variable {
			if bound[arg.Value.Raw] {
				return nil, "", fmt.Errorf("variable $%s bound twice", arg.Value.Raw)
			}
			bound[arg.Value.Raw] = true
			cand.bindings[arg.Name] = arg.Value.Raw
			continue
		}
		if containsVariable(arg.Value) {
			return nil, "", fmt.Errorf("argument %q nests a variable in a literal", arg.Name)
		}
		lit, err := astValueJSON(arg.Value, nil)
		if err != nil {
			return nil, "", fmt.Errorf("argument %q: %v", arg.Name, err)
		}
		cand.literals[arg.Name] = arg.Value
		cand.literalJSON[arg.Name] = lit
	}
	for name := range cand.varTypes {
		if !bound[name] {
			return nil, "", fmt.Errorf("variable $%s is not a root argument", name)
		}
	}
	for _, rule := range op.Variables {
		top, _, _ := strings.Cut(strings.ReplaceAll(rule.Path, "[*]", ""), ".")
		if !bound[top] {
			return nil, "", fmt.Errorf("variable rule %q names no root argument", rule.Path)
		}
	}
	return cand, field.Name, nil
}

func noNestedArguments(set ast.SelectionSet) error {
	for _, sel := range set {
		f, ok := sel.(*ast.Field)
		if !ok {
			return errors.New("document uses a fragment")
		}
		if len(f.Arguments) != 0 || len(f.Directives) != 0 {
			return fmt.Errorf("nested field %q has an argument or a directive", f.Name)
		}
		if err := noNestedArguments(f.SelectionSet); err != nil {
			return err
		}
	}
	return nil
}

func containsVariable(v *ast.Value) bool {
	if v == nil {
		return false
	}
	if v.Kind == ast.Variable {
		return true
	}
	for _, child := range v.Children {
		if containsVariable(child.Value) {
			return true
		}
	}
	return false
}

// astValueJSON converts an argument value to the variable-tree form the
// edge checks (json.Number for numbers, string for enums and strings). A
// variable reference is resolved from vars; an absent one is reported with
// errAbsentVariable.
func astValueJSON(v *ast.Value, vars map[string]any) (any, error) {
	switch v.Kind {
	case ast.Variable:
		value, ok := vars[v.Raw]
		if !ok {
			return nil, errAbsentVariable
		}
		return value, nil
	case ast.IntValue, ast.FloatValue:
		return json.Number(v.Raw), nil
	case ast.StringValue, ast.BlockValue, ast.EnumValue:
		return v.Raw, nil
	case ast.BooleanValue:
		return v.Raw == "true", nil
	case ast.NullValue:
		return nil, nil
	case ast.ListValue:
		out := make([]any, 0, len(v.Children))
		for _, child := range v.Children {
			item, err := astValueJSON(child.Value, vars)
			if errors.Is(err, errAbsentVariable) {
				item, err = nil, nil
			}
			if err != nil {
				return nil, err
			}
			out = append(out, item)
		}
		return out, nil
	case ast.ObjectValue:
		out := make(map[string]any, len(v.Children))
		for _, child := range v.Children {
			item, err := astValueJSON(child.Value, vars)
			if errors.Is(err, errAbsentVariable) {
				continue // an absent variable in an object is an absent field
			}
			if err != nil {
				return nil, err
			}
			out[child.Name] = item
		}
		return out, nil
	default:
		return nil, fmt.Errorf("value kind %d not handled", v.Kind)
	}
}

var errAbsentVariable = errors.New("variable not provided")

// Limits returns the caps.
func (p *GraphQLPolicy) Limits() GraphQLLimits { return p.limits }

// Catalogue returns the catalogue the policy was derived from.
func (p *GraphQLPolicy) Catalogue() *Catalogue { return p.catalogue }

// Schema returns the loaded ops SDL.
func (p *GraphQLPolicy) Schema() *ast.Schema { return p.schema }

// Root returns the policy of an allowed root field.
func (p *GraphQLPolicy) Root(field string) (*GraphQLRootPolicy, bool) {
	r, ok := p.roots[field]
	return r, ok
}

// Roots returns the allowed root fields, sorted.
func (p *GraphQLPolicy) Roots() []*GraphQLRootPolicy {
	out := make([]*GraphQLRootPolicy, 0, len(p.roots))
	for _, r := range p.roots {
		out = append(out, r)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Field < out[j].Field })
	return out
}

// RefusedRootFields lists the SDL Query fields that are not allowed, sorted
// (introspection fields excluded: they are refused by rule).
func (p *GraphQLPolicy) RefusedRootFields() []string {
	var out []string
	for _, f := range p.schema.Query.Fields {
		if strings.HasPrefix(f.Name, "__") {
			continue
		}
		if _, ok := p.roots[f.Name]; !ok {
			out = append(out, f.Name)
		}
	}
	sort.Strings(out)
	return out
}

// RootServedTo reports whether any candidate of the root is served to the
// caller class.
func (r *GraphQLRootPolicy) RootServedTo(class CallerClass) bool {
	for _, c := range r.candidates {
		if c.op.Scope(class).Served {
			return true
		}
	}
	return false
}

// narrowedTo returns a copy of op whose output allowlist is only the given
// paths (each must already be allowed). The copy is filter-only: it is
// never looked up by name.
func (op *OperationPolicy) narrowedTo(paths []string) *OperationPolicy {
	out := &OperationPolicy{Name: op.Name, outputs: map[string]OutputLeaf{}, nodes: map[string]bool{}}
	for _, path := range paths {
		leaf, ok := op.outputs[path]
		if !ok {
			continue
		}
		out.outputs[path] = leaf
		for prefix := parentPath(path); prefix != ""; prefix = parentPath(prefix) {
			out.nodes[prefix] = true
		}
	}
	return out
}

// graphqlRootsFile is the wire shape of graphql_roots.v1.json.
type graphqlRootsFile struct {
	Contract          string              `json:"contract"`
	Generator         string              `json:"generator"`
	SchemaDigest      string              `json:"schema_digest"`
	OperationsSource  string              `json:"operations_source"`
	Limits            GraphQLLimits       `json:"limits"`
	CostWeights       map[CostClass]int   `json:"cost_weights"`
	OperationTypes    []string            `json:"operation_types"`
	Roots             []graphqlRootsEntry `json:"roots"`
	RefusedRootFields []string            `json:"refused_root_fields"`
}

type graphqlRootsEntry struct {
	Field            string    `json:"field"`
	Operations       []string  `json:"operations"`
	CostClass        CostClass `json:"cost_class"`
	Arguments        []string  `json:"arguments"`
	FixedArguments   []string  `json:"fixed_arguments"`
	RestrictedServed bool      `json:"restricted_served"`
}

// RootsFileJSON renders contracts/mcp/graphql_roots.v1.json from the
// derived policy: the allowlist GWC's MCP listener must admit.
func (p *GraphQLPolicy) RootsFileJSON(generator string) ([]byte, error) {
	file := graphqlRootsFile{
		Contract:          GraphQLRootsContract,
		Generator:         generator,
		SchemaDigest:      p.catalogue.SchemaDigest(),
		OperationsSource:  "contracts/mcp/operations.v1.json",
		Limits:            p.limits,
		CostWeights:       map[CostClass]int{},
		OperationTypes:    []string{"query"},
		RefusedRootFields: p.RefusedRootFields(),
	}
	for _, class := range CostClassVocabulary() {
		file.CostWeights[class] = GraphQLCostWeight(class)
	}
	for _, root := range p.Roots() {
		args := map[string]bool{}
		fixed := map[string]bool{}
		for _, c := range root.candidates {
			for name := range c.bindings {
				args[name] = true
			}
			for name := range c.literals {
				args[name] = true
				fixed[name] = true
			}
		}
		// An argument bound by one candidate and fixed by another is not
		// fixed for the root.
		for _, c := range root.candidates {
			for name := range c.bindings {
				delete(fixed, name)
			}
		}
		file.Roots = append(file.Roots, graphqlRootsEntry{
			Field:            root.Field,
			Operations:       root.Operations(),
			CostClass:        root.CostClass(),
			Arguments:        sortedSet(args),
			FixedArguments:   sortedSet(fixed),
			RestrictedServed: root.RootServedTo(CallerRestricted),
		})
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(file); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func sortedSet(set map[string]bool) []string {
	out := make([]string, 0, len(set))
	for k := range set {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
