package directread

// Operation policy: the runtime loader of contracts/mcp/operations.v1.json
// (CHAOS-7036 design sections D.3 to D.7, table K14-A; slice S1a).
//
// The artifact is GENERATED by cmd/operationpolicy from the vendored ops
// catalogue (contracts/mcp/ops-catalogue/registry.v1.json + schema.graphql)
// and a hand-authored policy declaration. A byte-identical copy lives beside
// this file (operations.v1.json) so it can be embedded; a test holds the two
// equal and `go run ./cmd/operationpolicy -check` holds both equal to a fresh
// generation.
//
// Exported API (names are stable; the edge validator codes against them):
//
//	Loading
//	  DefaultCatalogue() (*Catalogue, error)   the embedded artifact, loaded once
//	  LoadCatalogue(data []byte) (*Catalogue, error)
//	  EmbeddedCatalogueJSON() []byte
//
//	Catalogue
//	  (*Catalogue).Lookup(name) (*OperationPolicy, *Refusal)
//	      a name that is not a served operation (a mutation, busFactor, a
//	      typo) is Refusal{Code: RefusalUnknownOperation}; for a listed
//	      not-served operation the Reason carries the recorded reason.
//	  (*Catalogue).LookupFor(name, CallerClass) (*OperationPolicy, CallerScope, *Refusal)
//	      adds RefusalOperationNotServedForCaller for a class the operation
//	      is refused to.
//	  (*Catalogue).Operations(CallerClass) []*OperationPolicy   sorted by name
//	  (*Catalogue).NotServed() []NotServedOperation
//	  (*Catalogue).SchemaDigest() string    ops goapidigest.Schema of the SDL
//	  (*Catalogue).Source() CatalogueSource
//
//	OperationPolicy (one served operation)
//	  Name, DocumentOperationName, Kind, Digest, DocumentText, CostClass,
//	  DeadlineSeconds, MaxInFlightPerOrg, Variables, PersonVariables,
//	  Constraints, Scopes, Outputs, WithheldOutputs, Disclosure
//	  (*OperationPolicy).Variable(path) (VariableRule, bool)
//	  (*OperationPolicy).Scope(CallerClass) CallerScope
//	  (*OperationPolicy).OutputAllowed(path) bool
//	  (*OperationPolicy).Completeness(data []byte) Completeness
//	  FilterResponse(op, data) (FilterResult, error)
//	      removes every response path the allowlist does not list; the
//	      caller ERROR-logs FilterResult.RemovedPaths / RemovedValues.
//
//	Variable rules (VariableRule): every input path the SDL allows for the
//	operation's variables, arrays as [*], objects included (Kind "object").
//	A rule with Allowed=false must be absent or JSON null in a request; its
//	Refusal says which code to answer. Source says who sets the value:
//	client, acr_principal_org (orgId from the principal, never the client),
//	acr_forced (ForcedValue). Enum rules carry AllowedValues and
//	RefusedValues (value -> code). Min/Max, MaxItems, MaxLength are clamps.
//	Subject (SubjectConversion) converts an acr subject id to the ops form:
//	(SubjectConversion).ToOps(acrID) (string, error).
//
//	Request-check rules the validator applies (allowlist semantics):
//	  - a request path with no rule is refused (variable_not_allowed);
//	  - a present, non-null path whose rule has Allowed=false is refused
//	    with that rule's Refusal; when several refused paths are present,
//	    report the DEEPEST one (who.developers answers
//	    person_scope_not_served, not the "who" object's code);
//	  - an enum value in RefusedValues answers that entry's code; a value
//	    in neither AllowedValues nor RefusedValues is variable_not_allowed;
//	  - Min/Max bound integers, MaxItems bounds lists, MaxLength bounds
//	    each string (variable_out_of_range);
//	  - acr_principal_org and acr_forced values are set by acr; a client
//	    value on such a path is refused (variable_not_allowed);
//	  - for a restricted caller, CallerScope.ForcedVariablePath is set to
//	    the grant intersection (converted with the rule's Subject); an
//	    empty intersection ends before dispatch (no_granted_scope); each
//	    RowIDPaths value of the answer must be in the grant, else the whole
//	    answer is refused (row_outside_grant).
//
//	Constraints (Constraint, kinds ConstraintRequired, ConstraintRequiresValue,
//	ConstraintEmptyOrAbsent, ConstraintWindowMaxDays, ConstraintMaxDaysAhead)
//	are cross-path rules; each carries its refusal Code and Reason.
//
//	Vocabularies: RefusalCode (RefusalCodeVocabulary), CallerClass,
//	CostClass, ConstraintKind, OutputLeaf, DisclosureRule, VariableSource;
//	status vocabulary in status.go (CallStatus, Completeness, ResultState).
//
//	Helpers shared with the generator: DocumentDigest, SchemaDigestOf,
//	ParseRegisteredDocument, IsPersonNamed, PersonNameTokens,
//	CallerClassFor(PrincipalClass).
//
// Load is fail closed: every served document is PARSED again, and must hold
// exactly one operation, of kind query, whose name equals the declared
// document_operation_name; its digest is recomputed and compared. Any
// violation, and any structural defect (unknown vocabulary, a person-named
// or free-JSON output path without a written exception, a row id path that
// is not an allowed output) is a load error. No network is used.

import (
	"bytes"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"slices"
	"sort"
	"strings"
	"sync"
	"sync/atomic"

	"github.com/vektah/gqlparser/v2/ast"
	"github.com/vektah/gqlparser/v2/parser"
)

// OperationCatalogueContract is the contract name the artifact carries.
const OperationCatalogueContract = "acr.mcp.operations.v1"

// BasisDependentShapeText is the fixed refusal text of table K14-A.
const BasisDependentShapeText = "team and repository investment comes from read_facts (kind investment)"

//go:embed operations.v1.json
var embeddedCatalogue []byte

// EmbeddedCatalogueJSON returns a copy of the embedded artifact bytes.
func EmbeddedCatalogueJSON() []byte { return bytes.Clone(embeddedCatalogue) }

// RefusalCode is the closed vocabulary of typed refusals of the data path.
type RefusalCode string

const (
	RefusalUnknownOperation            RefusalCode = "unknown_operation"
	RefusalVariableNotAllowed          RefusalCode = "variable_not_allowed"
	RefusalVariableOutOfRange          RefusalCode = "variable_out_of_range"
	RefusalPersonScopeNotServed        RefusalCode = "person_scope_not_served"
	RefusalBasisDependentShape         RefusalCode = "basis_dependent_shape"
	RefusalNoGrantedScope              RefusalCode = "no_granted_scope"
	RefusalOperationNotServedForCaller RefusalCode = "operation_not_served_for_caller"
	RefusalResponseBudget              RefusalCode = "response_budget"
	RefusalInvalidRequest              RefusalCode = "invalid_request"
	RefusalScopeRequired               RefusalCode = "scope_required"
	RefusalRowOutsideGrant             RefusalCode = "row_outside_grant"
	RefusalPolicyStale                 RefusalCode = "policy_stale"
)

// RefusalCodeVocabulary is the closed set of refusal codes.
func RefusalCodeVocabulary() [12]RefusalCode {
	return [12]RefusalCode{
		RefusalUnknownOperation, RefusalVariableNotAllowed, RefusalVariableOutOfRange,
		RefusalPersonScopeNotServed, RefusalBasisDependentShape, RefusalNoGrantedScope,
		RefusalOperationNotServedForCaller, RefusalResponseBudget, RefusalInvalidRequest,
		RefusalScopeRequired, RefusalRowOutsideGrant, RefusalPolicyStale,
	}
}

// Refusal is a typed, terminal refusal. It is never turned into empty data.
type Refusal struct {
	Code   RefusalCode `json:"code"`
	Reason string      `json:"reason"`
}

func (r *Refusal) Error() string { return string(r.Code) + ": " + r.Reason }

// CallerClass is the policy's view of a principal: unrestricted (no grant
// list, or the "*" grant) or restricted (a specific repository grant).
type CallerClass string

const (
	CallerUnrestricted CallerClass = "unrestricted"
	CallerRestricted   CallerClass = "restricted"
)

// CallerClassVocabulary is the closed set of caller classes.
func CallerClassVocabulary() [2]CallerClass {
	return [2]CallerClass{CallerUnrestricted, CallerRestricted}
}

// CallerClassFor maps the subject gate's principal class onto the policy's
// caller class: unrestricted and universal ("*") callers are unrestricted.
// Any unknown class is restricted (fail closed).
func CallerClassFor(class PrincipalClass) CallerClass {
	switch class {
	case ClassUnrestricted, ClassUniversal:
		return CallerUnrestricted
	default:
		return CallerRestricted
	}
}

// CostClass is the D.6 cost class.
type CostClass string

const (
	CostCompute        CostClass = "compute"
	CostAnalyticsBatch CostClass = "analytics_batch"
	CostList           CostClass = "list"
	CostSeries         CostClass = "series"
	CostCatalog        CostClass = "catalog"
)

// CostClassVocabulary is the closed set of cost classes.
func CostClassVocabulary() [5]CostClass {
	return [5]CostClass{CostCompute, CostAnalyticsBatch, CostList, CostSeries, CostCatalog}
}

// VariableSource says who sets a variable value.
type VariableSource string

const (
	SourceClient       VariableSource = "client"
	SourcePrincipalOrg VariableSource = "acr_principal_org"
	SourceForced       VariableSource = "acr_forced"
	SourceNotSettable  VariableSource = "none"
)

// Variable rule kinds and subject kinds.
const (
	VariableKindScalar    = "scalar"
	VariableKindEnum      = "enum"
	VariableKindObject    = "object"
	SubjectKindRepository = "repository"
	SubjectKindTeam       = "team"
)

// ConstraintKind is the closed vocabulary of cross-path constraints.
type ConstraintKind string

const (
	// ConstraintRequired: Path must be present and not null.
	ConstraintRequired ConstraintKind = "required"
	// ConstraintRequiresValue: when Path is present and not null, the value
	// at Other (or OtherDefault when Other is absent) must be in Values.
	// With an empty Path the rule is unconditional: Other must be in Values.
	ConstraintRequiresValue ConstraintKind = "requires_value"
	// ConstraintEmptyOrAbsent: Path must be absent, null or an empty list.
	ConstraintEmptyOrAbsent ConstraintKind = "empty_or_absent"
	// ConstraintWindowMaxDays: Path is the window start, Other the end
	// (absent end = now). end >= start and end - start <= MaxDays. An
	// absent start is refused unless AllowOpenStart.
	ConstraintWindowMaxDays ConstraintKind = "window_max_days"
	// ConstraintMaxDaysAhead: the date at Path is at most MaxDays after now.
	ConstraintMaxDaysAhead ConstraintKind = "max_days_ahead"
)

// ConstraintKindVocabulary is the closed set of constraint kinds.
func ConstraintKindVocabulary() [5]ConstraintKind {
	return [5]ConstraintKind{ConstraintRequired, ConstraintRequiresValue, ConstraintEmptyOrAbsent, ConstraintWindowMaxDays, ConstraintMaxDaysAhead}
}

// OutputLeaf classifies an allowlisted response path.
type OutputLeaf string

const (
	LeafScalar   OutputLeaf = "scalar"
	LeafJSON     OutputLeaf = "json"
	LeafTypename OutputLeaf = "typename"
)

// DisclosureRule is how a disclosure field maps to Completeness.
type DisclosureRule string

const (
	// DisclosurePartialWhenNonNull: a non-null value = declared_partial.
	DisclosurePartialWhenNonNull DisclosureRule = "partial_when_non_null"
	// DisclosurePartialWhenTrue: the value true = declared_partial.
	DisclosurePartialWhenTrue DisclosureRule = "partial_when_true"
	// DisclosurePartialWhenBelowOne: a number below 1 = declared_partial.
	DisclosurePartialWhenBelowOne DisclosureRule = "partial_when_below_one"
)

// CatalogueFile is the wire shape of operations.v1.json.
type CatalogueFile struct {
	Contract         string               `json:"contract"`
	Generator        string               `json:"generator"`
	Source           CatalogueSource      `json:"source"`
	PersonNameTokens []string             `json:"person_name_tokens"`
	Operations       []OperationPolicy    `json:"operations"`
	NotServed        []NotServedOperation `json:"not_served"`
}

// CatalogueSource pins what the artifact was generated from.
type CatalogueSource struct {
	Repository     string `json:"repository"`
	Commit         string `json:"commit"`
	Tool           string `json:"tool"`
	SchemaDigest   string `json:"schema_digest"`
	RegistrySHA256 string `json:"registry_sha256"`
	RegistryRows   int    `json:"registry_rows"`
}

// OperationPolicy is one served operation.
type OperationPolicy struct {
	Name                  string            `json:"name"`
	DocumentOperationName string            `json:"document_operation_name"`
	Kind                  string            `json:"kind"`
	Digest                string            `json:"digest"`
	DocumentText          string            `json:"document_text"`
	CostClass             CostClass         `json:"cost_class"`
	DeadlineSeconds       int               `json:"deadline_seconds"`
	MaxInFlightPerOrg     int               `json:"max_in_flight_per_org,omitempty"`
	Variables             []VariableRule    `json:"variables"`
	PersonVariables       []PersonVariable  `json:"person_variables"`
	Constraints           []Constraint      `json:"constraints"`
	Scopes                []CallerScope     `json:"scopes"`
	Outputs               []OutputPath      `json:"outputs"`
	WithheldOutputs       []WithheldOutput  `json:"withheld_outputs"`
	Disclosure            []DisclosureField `json:"disclosure"`
	Notes                 []string          `json:"notes,omitempty"`

	variables map[string]int
	outputs   map[string]OutputLeaf
	nodes     map[string]bool
}

// VariableRule is the rule for one input path.
type VariableRule struct {
	Path          string             `json:"path"`
	Type          string             `json:"type"`
	Kind          string             `json:"kind"`
	Enum          []string           `json:"enum,omitempty"`
	Default       string             `json:"default,omitempty"`
	Allowed       bool               `json:"allowed"`
	Source        VariableSource     `json:"source"`
	ForcedValue   json.RawMessage    `json:"forced_value,omitempty"`
	AllowedValues []string           `json:"allowed_values,omitempty"`
	RefusedValues []ValueRefusal     `json:"refused_values,omitempty"`
	Min           *int64             `json:"min,omitempty"`
	Max           *int64             `json:"max,omitempty"`
	MaxItems      int                `json:"max_items,omitempty"`
	MaxLength     int                `json:"max_length,omitempty"`
	Subject       *SubjectConversion `json:"subject,omitempty"`
	Refusal       *Refusal           `json:"refusal,omitempty"`
}

// ValueRefusal refuses one enum value with its own code.
type ValueRefusal struct {
	Value  string      `json:"value"`
	Code   RefusalCode `json:"code"`
	Reason string      `json:"reason"`
}

// SubjectConversion converts an acr subject id to the ops form.
type SubjectConversion struct {
	Kind      string `json:"kind"`
	AcrPrefix string `json:"acr_prefix"`
	OpsForm   string `json:"ops_form"`
}

// ToOps converts an acr subject id ("repository:<uuid>", "team:<id>") to the
// bare ops id. An id without the prefix, or with an empty or malformed
// remainder, is refused: acr never forwards a client string as an ops id.
func (s SubjectConversion) ToOps(acrID string) (string, error) {
	bare, ok := strings.CutPrefix(acrID, s.AcrPrefix)
	if !ok || s.AcrPrefix == "" || strings.TrimSpace(bare) != bare || bare == "" {
		return "", &Refusal{Code: RefusalInvalidRequest, Reason: "subject id is not a " + s.Kind + " id"}
	}
	if s.OpsForm == "bare_uuid" && !isUUID(bare) {
		return "", &Refusal{Code: RefusalInvalidRequest, Reason: "repository id is not a uuid"}
	}
	return bare, nil
}

func isUUID(s string) bool {
	if len(s) != 36 {
		return false
	}
	for i, r := range s {
		switch i {
		case 8, 13, 18, 23:
			if r != '-' {
				return false
			}
		default:
			if !strings.ContainsRune("0123456789abcdefABCDEF", r) {
				return false
			}
		}
	}
	return true
}

// PersonVariable is a person-scoped input found in the SDL walk: a whole
// path (Value empty) or one enum value of a path. Always refused.
type PersonVariable struct {
	Path  string `json:"path"`
	Value string `json:"value,omitempty"`
}

// Constraint is a cross-path rule.
type Constraint struct {
	Kind           ConstraintKind `json:"kind"`
	Path           string         `json:"path,omitempty"`
	Other          string         `json:"other,omitempty"`
	Values         []string       `json:"values,omitempty"`
	OtherDefault   string         `json:"other_default,omitempty"`
	MaxDays        int            `json:"max_days,omitempty"`
	AllowOpenStart bool           `json:"allow_open_start,omitempty"`
	Code           RefusalCode    `json:"code"`
	Reason         string         `json:"reason"`
}

// CallerScope is the operation's rule for one caller class.
type CallerScope struct {
	Caller             CallerClass  `json:"caller"`
	Served             bool         `json:"served"`
	ForcedVariablePath string       `json:"forced_variable_path,omitempty"`
	SubjectKind        string       `json:"subject_kind,omitempty"`
	RowIDPaths         []string     `json:"row_id_paths,omitempty"`
	UncheckedPaths     []string     `json:"unchecked_paths,omitempty"`
	Constraints        []Constraint `json:"constraints,omitempty"`
	Refusal            *Refusal     `json:"refusal,omitempty"`
	Basis              string       `json:"basis"`
}

// OutputPath is one allowlisted response path.
type OutputPath struct {
	Path      string     `json:"path"`
	Type      string     `json:"type"`
	Leaf      OutputLeaf `json:"leaf"`
	Exception string     `json:"exception,omitempty"`
	// BeyondDocument marks a path the registered document does not select:
	// graphql_query serves it, run_operation and recorded ops replies do not.
	BeyondDocument bool `json:"beyond_document,omitempty"`
}

// WithheldOutput is a path the document selects that never leaves acr.
type WithheldOutput struct {
	Path   string `json:"path"`
	Reason string `json:"reason"`
}

// DisclosureField is a field that states completeness.
type DisclosureField struct {
	Path string         `json:"path"`
	Rule DisclosureRule `json:"rule"`
}

// NotServedOperation is a registered ops document that the MCP surface does
// not serve, with the reason.
type NotServedOperation struct {
	Name   string      `json:"name"`
	Kind   string      `json:"kind"`
	Digest string      `json:"digest"`
	Code   RefusalCode `json:"code"`
	Reason string      `json:"reason"`
}

// EffectiveDefault is the default a client can rely on when it omits the
// variable: the generated SDL default, moved into [Min, Max] for an integer.
// data_catalog, the schema view and the cost clamp all read it, so the
// advertised value and the applied value cannot differ.
func (r VariableRule) EffectiveDefault() string {
	if baseTypeName(r.Type) != "Int" {
		return r.Default
	}
	var v int64
	if _, err := fmt.Sscan(r.Default, &v); err != nil || fmt.Sprint(v) != r.Default {
		return r.Default
	}
	if r.Max != nil && v > *r.Max {
		v = *r.Max
	}
	if r.Min != nil && v < *r.Min {
		v = *r.Min
	}
	return fmt.Sprint(v)
}

// Catalogue is a loaded, validated artifact.
type Catalogue struct {
	file      CatalogueFile
	byName    map[string]*OperationPolicy
	notServed map[string]NotServedOperation
	// watch is the optional served-registry check (registry_watch.go).
	watch atomic.Pointer[RegistryWatch]
}

var (
	defaultCatalogueOnce sync.Once
	defaultCatalogue     *Catalogue
	defaultCatalogueErr  error
)

// DefaultCatalogue loads the embedded artifact once.
func DefaultCatalogue() (*Catalogue, error) {
	defaultCatalogueOnce.Do(func() {
		defaultCatalogue, defaultCatalogueErr = LoadCatalogue(embeddedCatalogue)
	})
	return defaultCatalogue, defaultCatalogueErr
}

// ErrCatalogueInvalid wraps every load failure.
var ErrCatalogueInvalid = errors.New("operation catalogue invalid")

func loadErr(format string, args ...any) error {
	return fmt.Errorf("%w: %s", ErrCatalogueInvalid, fmt.Sprintf(format, args...))
}

// LoadCatalogue parses and validates an artifact. It is fail closed.
func LoadCatalogue(data []byte) (*Catalogue, error) {
	var file CatalogueFile
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&file); err != nil {
		return nil, loadErr("decode: %v", err)
	}
	if file.Contract != OperationCatalogueContract {
		return nil, loadErr("contract %q, want %q", file.Contract, OperationCatalogueContract)
	}
	if !slices.Equal(file.PersonNameTokens, PersonNameTokens()) {
		return nil, loadErr("person_name_tokens differ from the loader's list")
	}
	c := &Catalogue{file: file, byName: map[string]*OperationPolicy{}, notServed: map[string]NotServedOperation{}}
	for i := range c.file.Operations {
		op := &c.file.Operations[i]
		if err := validateOperation(op); err != nil {
			return nil, loadErr("operation %q: %v", op.Name, err)
		}
		if _, dup := c.byName[op.Name]; dup {
			return nil, loadErr("operation %q listed twice", op.Name)
		}
		c.byName[op.Name] = op
	}
	for _, ns := range c.file.NotServed {
		if ns.Name == "" || ns.Reason == "" || !knownRefusalCode(ns.Code) {
			return nil, loadErr("not_served entry %q lacks a name, a reason or a known code", ns.Name)
		}
		if _, dup := c.byName[ns.Name]; dup {
			return nil, loadErr("operation %q is both served and not served", ns.Name)
		}
		if _, dup := c.notServed[ns.Name]; dup {
			return nil, loadErr("not_served %q listed twice", ns.Name)
		}
		c.notServed[ns.Name] = ns
	}
	if got := len(c.byName) + len(c.notServed); got != file.Source.RegistryRows {
		return nil, loadErr("%d operations classified, registry has %d rows", got, file.Source.RegistryRows)
	}
	return c, nil
}

// RegisteredDocument is what ParseRegisteredDocument reports.
type RegisteredDocument struct {
	Kind string
	Name string
}

// Document kinds (the ops goapidigest.DocumentKind vocabulary).
const (
	DocumentKindQuery    = "query"
	DocumentKindMutation = "mutation"
)

// ParseRegisteredDocument is acr's copy of ops goapidigest.DocumentKind
// (internal/goapidigest/kind.go:28-44 at ops 9dffd5f77), plus the operation
// name: exactly one operation, of kind query or mutation. Anything else
// (unparseable, zero or several operations, a subscription) is an error.
func ParseRegisteredDocument(text string) (RegisteredDocument, error) {
	doc, err := parser.ParseQuery(&ast.Source{Name: "registered document", Input: text})
	if err != nil {
		return RegisteredDocument{}, fmt.Errorf("document does not parse: %w", err)
	}
	if len(doc.Operations) != 1 {
		return RegisteredDocument{}, fmt.Errorf("document has %d operations, want exactly 1", len(doc.Operations))
	}
	op := doc.Operations[0]
	switch op.Operation {
	case ast.Query:
		return RegisteredDocument{Kind: DocumentKindQuery, Name: op.Name}, nil
	case ast.Mutation:
		return RegisteredDocument{Kind: DocumentKindMutation, Name: op.Name}, nil
	default:
		return RegisteredDocument{}, fmt.Errorf("document operation type %q is not served by query-api", op.Operation)
	}
}

// DocumentDigest is acr's copy of ops goapidigest.Document: the hex sha256
// of strings.TrimSpace(text).
func DocumentDigest(text string) string {
	sum := sha256.Sum256([]byte(strings.TrimSpace(text)))
	return hex.EncodeToString(sum[:])
}

// SchemaDigestOf is acr's copy of ops goapidigest.Schema: "sha256:" + the
// hex sha256 of the RAW SDL bytes.
func SchemaDigestOf(sdl []byte) string {
	sum := sha256.Sum256(sdl)
	return "sha256:" + hex.EncodeToString(sum[:])
}

// personNameTokens is design D.5's list of person-named path segments. A
// segment matches when its lower-cased form CONTAINS a token, so plurals
// and compounds (topMaintainers, developers, triggeredBy's "createdby" kin)
// match too. Over-matching fails closed: it forces a written exception.
var personNameTokens = []string{
	"actor", "assignee", "author", "committer", "createdby", "developer",
	"email", "identity", "login", "maintainer", "reviewer", "user",
}

// PersonNameTokens returns the person-name tokens.
func PersonNameTokens() []string { return slices.Clone(personNameTokens) }

// IsPersonNamed reports whether a path segment (field name, enum value or
// input field name) names a person.
func IsPersonNamed(segment string) bool {
	lower := strings.ToLower(segment)
	for _, token := range personNameTokens {
		if strings.Contains(lower, token) {
			return true
		}
	}
	return false
}

// pathSegments splits "a.b[*].c" into field names ("a", "b", "c").
func pathSegments(path string) []string {
	parts := strings.Split(strings.ReplaceAll(path, "[*]", ""), ".")
	return parts
}

func validateOperation(op *OperationPolicy) error {
	if op.Name == "" || op.DocumentOperationName == "" {
		return errors.New("name or document_operation_name empty")
	}
	if op.Kind != DocumentKindQuery {
		return fmt.Errorf("declared kind %q, want query", op.Kind)
	}
	parsed, err := ParseRegisteredDocument(op.DocumentText)
	if err != nil {
		return err
	}
	if parsed.Kind != DocumentKindQuery {
		return fmt.Errorf("document parses as %s, want query", parsed.Kind)
	}
	if parsed.Name != op.DocumentOperationName {
		return fmt.Errorf("document operation name %q, declared %q", parsed.Name, op.DocumentOperationName)
	}
	if got := DocumentDigest(op.DocumentText); got != op.Digest {
		return fmt.Errorf("digest %s, recomputed %s", op.Digest, got)
	}
	if !knownCostClass(op.CostClass) {
		return fmt.Errorf("cost class %q not in vocabulary", op.CostClass)
	}
	if op.DeadlineSeconds <= 0 {
		return errors.New("deadline_seconds must be positive")
	}
	op.variables = map[string]int{}
	for i, v := range op.Variables {
		if _, dup := op.variables[v.Path]; dup {
			return fmt.Errorf("variable %q listed twice", v.Path)
		}
		op.variables[v.Path] = i
		if v.Allowed == (v.Refusal != nil) {
			return fmt.Errorf("variable %q: allowed and refusal must be exclusive", v.Path)
		}
		if v.Refusal != nil && !knownRefusalCode(v.Refusal.Code) {
			return fmt.Errorf("variable %q: refusal code %q not in vocabulary", v.Path, v.Refusal.Code)
		}
		if v.Allowed && v.Source == SourceNotSettable {
			return fmt.Errorf("variable %q: allowed with source none", v.Path)
		}
		for _, rv := range v.RefusedValues {
			if !knownRefusalCode(rv.Code) || slices.Contains(v.AllowedValues, rv.Value) {
				return fmt.Errorf("variable %q: refused value %q invalid", v.Path, rv.Value)
			}
		}
		for _, av := range v.AllowedValues {
			if !slices.Contains(v.Enum, av) {
				return fmt.Errorf("variable %q: allowed value %q not in the enum", v.Path, av)
			}
		}
	}
	for _, pv := range op.PersonVariables {
		i, ok := op.variables[pv.Path]
		if !ok {
			return fmt.Errorf("person variable %q is not a listed path", pv.Path)
		}
		rule := op.Variables[i]
		if pv.Value == "" && rule.Allowed {
			return fmt.Errorf("person variable %q is allowed", pv.Path)
		}
		if pv.Value != "" && slices.Contains(rule.AllowedValues, pv.Value) {
			return fmt.Errorf("person value %s=%s is allowed", pv.Path, pv.Value)
		}
	}
	for _, v := range op.Variables {
		if v.Allowed && v.Kind == VariableKindEnum && len(v.AllowedValues) == 0 {
			return fmt.Errorf("enum variable %q allowed with no allowed values", v.Path)
		}
		for _, av := range v.AllowedValues {
			if IsPersonNamed(av) {
				return fmt.Errorf("person value %s=%s is allowed", v.Path, av)
			}
		}
		if v.Allowed && slices.ContainsFunc(pathSegments(v.Path), IsPersonNamed) {
			return fmt.Errorf("person-named variable %q is allowed", v.Path)
		}
	}
	allConstraints := slices.Clone(op.Constraints)
	op.outputs = map[string]OutputLeaf{}
	op.nodes = map[string]bool{}
	for _, out := range op.Outputs {
		if _, dup := op.outputs[out.Path]; dup {
			return fmt.Errorf("output %q listed twice", out.Path)
		}
		switch out.Leaf {
		case LeafScalar, LeafTypename:
		case LeafJSON:
			if out.Exception == "" {
				return fmt.Errorf("free JSON output %q without a written exception", out.Path)
			}
		default:
			return fmt.Errorf("output %q: leaf %q not in vocabulary", out.Path, out.Leaf)
		}
		if slices.ContainsFunc(pathSegments(out.Path), IsPersonNamed) && out.Exception == "" {
			return fmt.Errorf("person-named output %q without a written exception", out.Path)
		}
		op.outputs[out.Path] = out.Leaf
		for prefix := parentPath(out.Path); prefix != ""; prefix = parentPath(prefix) {
			op.nodes[prefix] = true
		}
	}
	if len(op.outputs) == 0 {
		return errors.New("no output path")
	}
	for _, w := range op.WithheldOutputs {
		if _, listed := op.outputs[w.Path]; listed || w.Reason == "" {
			return fmt.Errorf("withheld output %q is also allowed or has no reason", w.Path)
		}
	}
	for _, d := range op.Disclosure {
		if _, ok := op.outputs[d.Path]; !ok {
			return fmt.Errorf("disclosure field %q is not an allowed output", d.Path)
		}
	}
	seen := map[CallerClass]bool{}
	for _, s := range op.Scopes {
		if !knownCallerClass(s.Caller) || seen[s.Caller] {
			return fmt.Errorf("scope caller %q unknown or repeated", s.Caller)
		}
		seen[s.Caller] = true
		if s.Served == (s.Refusal != nil) {
			return fmt.Errorf("scope %q: served and refusal must be exclusive", s.Caller)
		}
		if s.Basis == "" {
			return fmt.Errorf("scope %q: no basis", s.Caller)
		}
		if s.Caller == CallerRestricted && s.Served {
			if s.ForcedVariablePath == "" || len(s.RowIDPaths) == 0 || s.SubjectKind != SubjectKindRepository {
				return errors.New("restricted scope served without forced repository path and row id paths")
			}
			forced, ok := op.Variable(s.ForcedVariablePath)
			if !ok {
				return fmt.Errorf("forced path %q is not a listed variable", s.ForcedVariablePath)
			}
			if !forced.Allowed || forced.Subject == nil || forced.Subject.Kind != SubjectKindRepository {
				return fmt.Errorf("forced path %q is not an allowed repository variable", s.ForcedVariablePath)
			}
			for _, row := range s.RowIDPaths {
				if op.outputs[row] != LeafScalar {
					return fmt.Errorf("row id path %q is not an allowed scalar output", row)
				}
			}
		}
		allConstraints = append(allConstraints, s.Constraints...)
	}
	if len(seen) != len(CallerClassVocabulary()) {
		return errors.New("scopes must cover every caller class")
	}
	if !seen[CallerUnrestricted] {
		return errors.New("no unrestricted scope")
	}
	if op.Scope(CallerUnrestricted).Refusal != nil {
		return errors.New("a served operation must be served to the unrestricted caller")
	}
	for _, con := range allConstraints {
		if !knownConstraintKind(con.Kind) || !knownRefusalCode(con.Code) || con.Reason == "" {
			return fmt.Errorf("constraint %s on %q: kind, code or reason invalid", con.Kind, con.Path)
		}
		for _, p := range []string{con.Path, con.Other} {
			if _, ok := op.variables[p]; p != "" && !ok {
				return fmt.Errorf("constraint %s names unknown path %q", con.Kind, p)
			}
		}
	}
	return nil
}

// parentPath returns the enclosing node of a path: "a.b[*].c" -> "a.b[*]"
// -> "a.b" -> "a" -> "".
func parentPath(path string) string {
	if trimmed, ok := strings.CutSuffix(path, "[*]"); ok {
		return trimmed
	}
	if i := strings.LastIndex(path, "."); i >= 0 {
		return path[:i]
	}
	return ""
}

// Source returns what the artifact was generated from.
func (c *Catalogue) Source() CatalogueSource { return c.file.Source }

// SchemaDigest returns the ops schema digest the artifact was generated
// against (ops goapidigest.Schema form).
func (c *Catalogue) SchemaDigest() string { return c.file.Source.SchemaDigest }

// Lookup returns the served operation, or a RefusalUnknownOperation refusal
// for any other name. It never dials anything.
func (c *Catalogue) Lookup(name string) (*OperationPolicy, *Refusal) {
	if op, ok := c.byName[name]; ok {
		return op, nil
	}
	if ns, ok := c.notServed[name]; ok {
		return nil, &Refusal{Code: RefusalUnknownOperation, Reason: ns.Reason}
	}
	return nil, &Refusal{Code: RefusalUnknownOperation, Reason: "operation is not in the served catalogue"}
}

// LookupFor is Lookup plus the caller-class rule.
func (c *Catalogue) LookupFor(name string, caller CallerClass) (*OperationPolicy, CallerScope, *Refusal) {
	op, refusal := c.Lookup(name)
	if refusal != nil {
		return nil, CallerScope{}, refusal
	}
	scope := op.Scope(caller)
	if !scope.Served {
		if scope.Refusal != nil {
			return nil, scope, scope.Refusal
		}
		return nil, scope, &Refusal{Code: RefusalOperationNotServedForCaller, Reason: "operation is not served to this caller class"}
	}
	return op, scope, nil
}

// Operations returns the operations served to a caller class, by name.
func (c *Catalogue) Operations(caller CallerClass) []*OperationPolicy {
	out := make([]*OperationPolicy, 0, len(c.byName))
	for _, op := range c.byName {
		if op.Scope(caller).Served {
			out = append(out, op)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// NotServed returns the registered operations the surface does not serve.
func (c *Catalogue) NotServed() []NotServedOperation { return slices.Clone(c.file.NotServed) }

// Variable returns the rule of one input path.
func (op *OperationPolicy) Variable(path string) (VariableRule, bool) {
	i, ok := op.variables[path]
	if !ok {
		return VariableRule{}, false
	}
	return op.Variables[i], true
}

// Scope returns the rule for a caller class. An unknown class is refused.
func (op *OperationPolicy) Scope(caller CallerClass) CallerScope {
	for _, s := range op.Scopes {
		if s.Caller == caller {
			return s
		}
	}
	return CallerScope{Caller: caller, Refusal: &Refusal{Code: RefusalOperationNotServedForCaller, Reason: "unknown caller class"}}
}

// OutputAllowed reports whether a response leaf path may leave acr.
func (op *OperationPolicy) OutputAllowed(path string) bool {
	_, ok := op.outputs[path]
	return ok
}

// FilterResult is what FilterResponse returns.
type FilterResult struct {
	// Data is the filtered "data" object.
	Data json.RawMessage
	// RemovedPaths are the distinct generalized paths ("a.b[*].c") removed.
	RemovedPaths []string
	// RemovedValues counts every removed value. Non-zero = ERROR log.
	RemovedValues int
}

// FilterResponse removes from a GraphQL "data" object every path that is
// not on the operation's output allowlist. A non-JSON leaf that carries an
// object or a list of objects is removed as well: an allowlisted scalar
// path never smuggles nested data. The caller ERROR-logs a non-zero result.
func FilterResponse(op *OperationPolicy, data []byte) (FilterResult, error) {
	if op == nil || op.outputs == nil {
		return FilterResult{}, errors.New("filter: operation policy not loaded")
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	var root any
	if err := dec.Decode(&root); err != nil {
		return FilterResult{}, fmt.Errorf("filter: decode: %w", err)
	}
	f := &responseFilter{op: op, removed: map[string]bool{}}
	obj, ok := root.(map[string]any)
	if !ok {
		if root == nil {
			return FilterResult{Data: json.RawMessage("null")}, nil
		}
		return FilterResult{}, errors.New("filter: data is not an object")
	}
	kept := f.object("", obj)
	out, err := json.Marshal(kept)
	if err != nil {
		return FilterResult{}, fmt.Errorf("filter: encode: %w", err)
	}
	paths := make([]string, 0, len(f.removed))
	for p := range f.removed {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	return FilterResult{Data: out, RemovedPaths: paths, RemovedValues: f.count}, nil
}

type responseFilter struct {
	op      *OperationPolicy
	removed map[string]bool
	count   int
}

func joinPath(parent, key string) string {
	if parent == "" {
		return key
	}
	return parent + "." + key
}

func (f *responseFilter) remove(path string) {
	f.removed[path] = true
	f.count++
}

func (f *responseFilter) object(path string, obj map[string]any) map[string]any {
	out := make(map[string]any, len(obj))
	for key, value := range obj {
		child := joinPath(path, key)
		if kept, ok := f.value(child, value); ok {
			out[key] = kept
		}
	}
	return out
}

func (f *responseFilter) value(path string, value any) (any, bool) {
	leaf, isLeaf := f.op.outputs[path]
	if leaf == LeafJSON {
		// A free-JSON leaf is a written exception for a flat band -> number
		// map (ops investment/response.go:34,46). Anything richer could carry
		// a person field the path allowlist cannot see, so it is removed.
		if value != nil && !flatNumberMap(value) {
			f.remove(path)
			return nil, false
		}
		return value, true
	}
	switch v := value.(type) {
	case nil:
		if isLeaf || f.op.nodes[path] {
			return nil, true
		}
		f.remove(path)
		return nil, false
	case map[string]any:
		if !f.op.nodes[path] {
			f.remove(path)
			return nil, false
		}
		return f.object(path, v), true
	case []any:
		elem := path + "[*]"
		_, elemLeaf := f.op.outputs[elem]
		if !elemLeaf && !f.op.nodes[elem] {
			f.remove(path)
			return nil, false
		}
		out := make([]any, 0, len(v))
		for _, item := range v {
			if kept, ok := f.value(elem, item); ok {
				out = append(out, kept)
			}
		}
		return out, true
	default:
		if isLeaf {
			return v, true
		}
		f.remove(path)
		return nil, false
	}
}

// Completeness applies the operation's disclosure fields to a "data" object
// (D.7). Without a disclosure field the answer is always unknown.
func (op *OperationPolicy) Completeness(data []byte) Completeness {
	if len(op.Disclosure) == 0 {
		return CompletenessUnknown
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	var root any
	if dec.Decode(&root) != nil {
		return CompletenessUnknown
	}
	for _, d := range op.Disclosure {
		value, present := lookupScalarPath(root, d.Path)
		if !present {
			continue
		}
		switch d.Rule {
		case DisclosurePartialWhenNonNull:
			if value != nil {
				return CompletenessDeclaredPartial
			}
		case DisclosurePartialWhenTrue:
			if b, ok := value.(bool); ok && b {
				return CompletenessDeclaredPartial
			}
		case DisclosurePartialWhenBelowOne:
			if n, ok := value.(json.Number); ok {
				if x, err := n.Float64(); err == nil && x < 1 {
					return CompletenessDeclaredPartial
				}
			}
		}
	}
	return CompletenessUnknown
}

func lookupScalarPath(root any, path string) (any, bool) {
	cur := root
	for _, seg := range strings.Split(path, ".") {
		obj, ok := cur.(map[string]any)
		if !ok {
			return nil, false
		}
		cur, ok = obj[seg]
		if !ok {
			return nil, false
		}
	}
	return cur, true
}

func knownRefusalCode(v RefusalCode) bool {
	vocab := RefusalCodeVocabulary()
	return slices.Contains(vocab[:], v)
}
func knownCostClass(v CostClass) bool {
	vocab := CostClassVocabulary()
	return slices.Contains(vocab[:], v)
}
func knownCallerClass(v CallerClass) bool {
	vocab := CallerClassVocabulary()
	return slices.Contains(vocab[:], v)
}
func knownConstraintKind(v ConstraintKind) bool {
	vocab := ConstraintKindVocabulary()
	return slices.Contains(vocab[:], v)
}

// flatNumberMap reports whether v is a JSON object whose keys are not
// person-named and whose values are all numbers or null (depth one). It is
// the only shape a free-JSON output leaf may have.
func flatNumberMap(v any) bool {
	obj, ok := v.(map[string]any)
	if !ok {
		return false
	}
	for key, value := range obj {
		if IsPersonNamed(key) {
			return false
		}
		switch value.(type) {
		case nil, json.Number, float64:
		default:
			return false
		}
	}
	return true
}
