package contextpacket

const standardColumns = `SELECT evidence_ref_id, system, entity_type, entity_id, display_label, safe_uri, provenance, toFloat64(confidence) confidence, citation, observed_at FROM (`

const SourceQueryCatalogVersionV1 = "dev-health-source-catalog.v1"

// Provenance is the first evidence-ranking key, so these adapters map only raw
// values whose meaning has been reviewed for that source. Every final empty
// string is deliberately outside the fixed provenance enum: unknown input must
// fail downstream validation without returning or logging the raw value. Never
// replace an invalid fallback with a valid default; that launders corrupt data
// into ranked evidence.

// aiWorkflowArtifactProvenanceMapping maps:
//   - 'pr_body' -> 'explicit_text': the linkage was stated in human-authored PR text.
//   - 'branch_name' -> 'heuristic': the linkage was inferred from a naming convention.
//   - 'native' -> 'native': the upstream artifact relation is already canonical evidence.
const aiWorkflowArtifactProvenanceMapping = `multiIf(source = 'pr_body', 'explicit_text', source = 'branch_name', 'heuristic', source = 'native', 'native', '')`

// aiReviewOutcomeProvenanceMapping maps:
//   - 'native' -> 'native': the review outcome relation is recorded directly by its source.
const aiReviewOutcomeProvenanceMapping = `multiIf(source = 'native', 'native', '')`

// deploymentIncidentProvenanceMapping maps:
//   - 'native' -> 'native': the source directly records the deployment-incident relation.
//   - 'heuristic' -> 'heuristic': the source inferred the correlation rather than asserting it.
const deploymentIncidentProvenanceMapping = `multiIf(source = 'native', 'native', source = 'heuristic', 'heuristic', '')`

// incidentRelationshipProvenanceMapping maps:
//   - 'bounded_service_repository_heuristic' -> 'heuristic': the relationship is explicitly inferred.
//   - 'native' -> 'native': the relationship is source-native.
//   - 'native_repository_context' -> 'native': repository context is source-native.
//   - 'admin_configuration' -> 'native': an administrator explicitly configured the relationship.
//   - 'pagerduty_service_metadata' -> 'native': authoritative service metadata supplies the relationship.
//   - 'compass_service_catalog' -> 'native': authoritative catalog metadata supplies the relationship.
//   - 'explicit_text' -> 'explicit_text': the value already uses the canonical authored-text meaning.
//   - 'heuristic' -> 'heuristic': the value already uses the canonical inference meaning.
//   - 'derived' -> 'derived': the value already uses the canonical computed-fact meaning.
const incidentRelationshipProvenanceMapping = `multiIf(m.relationship_provenance = 'bounded_service_repository_heuristic', 'heuristic', m.relationship_provenance IN ('native', 'native_repository_context', 'admin_configuration', 'pagerduty_service_metadata', 'compass_service_catalog'), 'native', m.relationship_provenance IN ('explicit_text', 'heuristic', 'derived'), m.relationship_provenance, '')`

// Each projection is scoped by independently bound authenticated org_id and
// server-resolved repo_id. FINAL is required for ReplacingMergeTree sources.
var SourceQueryCatalogV1 = []SourceQuery{
	{"repository_freshness.v1", "repository", EvidenceScopeBranch, standardColumns + ` SELECT concat('acr:v1:repository:', toString(id)) evidence_ref_id, 'dev_health' system, 'repository' entity_type, toString(id) entity_id, repo display_label, '' safe_uri, 'native' provenance, 1.0 confidence, 'repository freshness' citation, last_synced observed_at FROM repos FINAL WHERE org_id = {org_id:String} AND id = {repo_id:UUID} AND repo = {repo_slug:String} AND ({branch:String} = '' OR ref = {branch:String}) AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR last_synced <= {as_of:Nullable(DateTime64(3, 'UTC'))}) )`},
	{"work_items.v1", "work_items", EvidenceScopeRepo, standardColumns + ` SELECT concat('acr:v1:work-item:', work_item_id) evidence_ref_id, 'dev_health' system, 'work_item' entity_type, work_item_id entity_id, title display_label, url safe_uri, 'native' provenance, 1.0 confidence, status citation, updated_at observed_at FROM work_items FINAL WHERE org_id = {org_id:String} AND repo_id = {repo_id:UUID} AND ({task_ref:String} = '' OR work_item_id = {task_ref:String}) AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR updated_at <= {as_of:Nullable(DateTime64(3, 'UTC'))}) AND ({time_window_days:UInt16} = 0 OR updated_at >= coalesce({as_of:Nullable(DateTime64(3, 'UTC'))}, now64(3)) - toIntervalDay({time_window_days:UInt16})) )`},
	{"work_item_dependencies.v1", "work_items", EvidenceScopeRepo, standardColumns + ` SELECT concat('acr:v1:work-item-dependency:', d.source_work_item_id, ':', d.target_work_item_id) evidence_ref_id, 'dev_health' system, 'work_item_dependency' entity_type, concat(d.source_work_item_id, ':', d.target_work_item_id) entity_id, concat(d.source_work_item_id, ' ', d.relationship_type, ' ', d.target_work_item_id) display_label, '' safe_uri, 'native' provenance, 1.0 confidence, d.relationship_type_raw citation, d.last_synced observed_at FROM work_item_dependencies AS d FINAL INNER JOIN work_items AS w FINAL ON d.source_work_item_id = w.work_item_id WHERE d.org_id = {org_id:String} AND w.org_id = {org_id:String} AND w.repo_id = {repo_id:UUID} AND ({task_ref:String} = '' OR d.source_work_item_id = {task_ref:String} OR d.target_work_item_id = {task_ref:String}) AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR d.last_synced <= {as_of:Nullable(DateTime64(3, 'UTC'))}) )`},
	{"git_commits.v1", "git", EvidenceScopeCommit, standardColumns + ` SELECT concat('acr:v1:commit:', c.hash) evidence_ref_id, 'dev_health' system, 'commit' entity_type, c.hash entity_id, ifNull(c.message, c.hash) display_label, '' safe_uri, 'native' provenance, 1.0 confidence, ifNull(c.message, '') citation, c.committer_when observed_at FROM git_commits AS c FINAL INNER JOIN repos AS repo FINAL ON repo.id = c.repo_id WHERE repo.org_id = {org_id:String} AND repo.id = {repo_id:UUID} AND ({commit_sha:String} = '' OR c.hash = {commit_sha:String}) AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR c.committer_when <= {as_of:Nullable(DateTime64(3, 'UTC'))}) AND ({time_window_days:UInt16} = 0 OR c.committer_when >= coalesce({as_of:Nullable(DateTime64(3, 'UTC'))}, now64(3)) - toIntervalDay({time_window_days:UInt16})) )`},
	{"git_commit_files.v1", "git", EvidenceScopeCommit, standardColumns + ` SELECT concat('acr:v1:commit-file:', c.commit_hash, ':', c.file_path) evidence_ref_id, 'dev_health' system, 'commit_file' entity_type, concat(c.commit_hash, ':', c.file_path) entity_id, c.file_path display_label, '' safe_uri, 'native' provenance, 1.0 confidence, concat(toString(c.additions), ' additions, ', toString(c.deletions), ' deletions') citation, c.last_synced observed_at FROM git_commit_stats AS c FINAL INNER JOIN repos AS repo FINAL ON repo.id = c.repo_id WHERE repo.org_id = {org_id:String} AND repo.id = {repo_id:UUID} AND ({commit_sha:String} = '' OR c.commit_hash = {commit_sha:String}) AND (empty({files:Array(String)}) OR has({files:Array(String)}, c.file_path)) AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR c.last_synced <= {as_of:Nullable(DateTime64(3, 'UTC'))}) )`},
	{"pull_requests.v1", "git", EvidenceScopeBranch, standardColumns + ` SELECT concat('acr:v1:pull-request:', toString(p.number)) evidence_ref_id, 'dev_health' system, 'pull_request' entity_type, toString(p.number) entity_id, ifNull(p.title, concat('PR #', toString(p.number))) display_label, '' safe_uri, 'native' provenance, 1.0 confidence, ifNull(p.state, '') citation, p.last_synced observed_at FROM git_pull_requests AS p FINAL INNER JOIN repos AS repo FINAL ON repo.id = p.repo_id WHERE repo.org_id = {org_id:String} AND repo.id = {repo_id:UUID} AND ({branch:String} = '' OR p.head_branch = {branch:String} OR p.base_branch = {branch:String}) AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR p.last_synced <= {as_of:Nullable(DateTime64(3, 'UTC'))}) AND ({time_window_days:UInt16} = 0 OR p.last_synced >= coalesce({as_of:Nullable(DateTime64(3, 'UTC'))}, now64(3)) - toIntervalDay({time_window_days:UInt16})) )`},
	{"pull_request_reviews.v1", "git", EvidenceScopeBranch, standardColumns + ` SELECT concat('acr:v1:review:', r.review_id) evidence_ref_id, 'dev_health' system, 'pull_request_review' entity_type, r.review_id entity_id, concat('PR #', toString(r.number), ' review') display_label, '' safe_uri, 'native' provenance, 1.0 confidence, r.state citation, r.submitted_at observed_at FROM git_pull_request_reviews AS r FINAL INNER JOIN git_pull_requests AS p FINAL ON r.repo_id = p.repo_id AND r.number = p.number INNER JOIN repos AS repo FINAL ON repo.id = r.repo_id WHERE repo.org_id = {org_id:String} AND repo.id = {repo_id:UUID} AND ({branch:String} = '' OR p.head_branch = {branch:String} OR p.base_branch = {branch:String}) AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR r.submitted_at <= {as_of:Nullable(DateTime64(3, 'UTC'))}) AND ({time_window_days:UInt16} = 0 OR r.submitted_at >= coalesce({as_of:Nullable(DateTime64(3, 'UTC'))}, now64(3)) - toIntervalDay({time_window_days:UInt16})) )`},
	{"ci_pipeline_runs.v1", "ci", EvidenceScopeBranch, standardColumns + ` SELECT concat('acr:v1:ci:', c.run_id) evidence_ref_id, 'dev_health' system, 'ci_pipeline_run' entity_type, c.run_id entity_id, concat('CI ', c.run_id) display_label, '' safe_uri, 'native' provenance, 1.0 confidence, ifNull(c.status, '') citation, coalesce(c.finished_at, c.started_at) observed_at FROM ci_pipeline_runs AS c FINAL INNER JOIN repos AS repo FINAL ON repo.id = c.repo_id WHERE repo.org_id = {org_id:String} AND repo.id = {repo_id:UUID} AND ({branch:String} = '' OR c.branch = {branch:String}) AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR c.started_at <= {as_of:Nullable(DateTime64(3, 'UTC'))}) AND ({time_window_days:UInt16} = 0 OR c.started_at >= coalesce({as_of:Nullable(DateTime64(3, 'UTC'))}, now64(3)) - toIntervalDay({time_window_days:UInt16})) )`},
	{"work_graph.v1", "work_graph", EvidenceScopeRepo, standardColumns + ` SELECT concat('acr:v1:graph:', edge_id) evidence_ref_id, 'dev_health' system, 'work_graph_edge' entity_type, edge_id entity_id, concat(source_id, ' ', edge_type, ' ', target_id) display_label, '' safe_uri, provenance, confidence, evidence citation, discovered_at observed_at FROM work_graph_edges FINAL WHERE org_id = {org_id:String} AND repo_id = {repo_id:UUID} AND ({task_ref:String} = '' OR source_id = {task_ref:String} OR target_id = {task_ref:String}) AND ({commit_sha:String} = '' OR source_id = {commit_sha:String} OR target_id = {commit_sha:String}) AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR discovered_at <= {as_of:Nullable(DateTime64(3, 'UTC'))}) )`},
	{"ai_workflow_runs.v1", "ai_workflow", EvidenceScopeRepo, standardColumns + ` SELECT concat('acr:v1:ai-run:', run_id) evidence_ref_id, 'dev_health' system, 'ai_workflow_run' entity_type, run_id entity_id, concat(provider, ' ', run_kind, ' ', ifNull(status, 'unknown')) display_label, '' safe_uri, 'native' provenance, 1.0 confidence, ifNull(status, '') citation, observed_at FROM ai_workflow_runs FINAL WHERE toString(org_id) = {org_id:String} AND repo_id = {repo_id:UUID} AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR observed_at <= {as_of:Nullable(DateTime64(3, 'UTC'))}) AND ({time_window_days:UInt16} = 0 OR observed_at >= coalesce({as_of:Nullable(DateTime64(3, 'UTC'))}, now64(3)) - toIntervalDay({time_window_days:UInt16})) )`},
	{"ai_workflow_artifacts.v1", "ai_workflow", EvidenceScopeRepo, standardColumns + ` SELECT concat('acr:v1:ai-artifact:', edge_id) evidence_ref_id, 'dev_health' system, artifact_type entity_type, artifact_id entity_id, concat('AI artifact ', artifact_id) display_label, '' safe_uri, ` + aiWorkflowArtifactProvenanceMapping + ` provenance, confidence, evidence citation, observed_at FROM ai_workflow_artifact_edges FINAL WHERE toString(org_id) = {org_id:String} AND repo_id = {repo_id:UUID} AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR observed_at <= {as_of:Nullable(DateTime64(3, 'UTC'))}) )`},
	{"ai_review_outcomes.v1", "ai_workflow", EvidenceScopeRepo, standardColumns + ` SELECT concat('acr:v1:review-outcome:', edge_id) evidence_ref_id, 'dev_health' system, 'review_outcome' entity_type, review_outcome_id entity_id, concat('PR ', pr_id, ' review outcome') display_label, '' safe_uri, ` + aiReviewOutcomeProvenanceMapping + ` provenance, confidence, concat(ifNull(outcome, ''), ': ', evidence) citation, observed_at FROM work_graph_pr_review_outcome_edges FINAL WHERE toString(org_id) = {org_id:String} AND repo_id = {repo_id:UUID} AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR observed_at <= {as_of:Nullable(DateTime64(3, 'UTC'))}) )`},
	{"deployments.v1", "delivery", EvidenceScopeRepo, standardColumns + ` SELECT concat('acr:v1:deployment:', d.deployment_id) evidence_ref_id, 'dev_health' system, 'deployment' entity_type, d.deployment_id entity_id, concat(ifNull(d.environment, 'unknown'), ' deployment') display_label, '' safe_uri, 'native' provenance, d.release_ref_confidence confidence, if(d.release_ref != '', concat('release_ref=', d.release_ref), concat('deployment_id=', d.deployment_id)) citation, coalesce(d.deployed_at, d.started_at, d.last_synced) observed_at FROM deployments AS d FINAL INNER JOIN repos AS repo FINAL ON repo.id = d.repo_id WHERE repo.org_id = {org_id:String} AND repo.id = {repo_id:UUID} AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR coalesce(d.deployed_at, d.started_at, d.last_synced) <= {as_of:Nullable(DateTime64(3, 'UTC'))}) )`},
	{"incidents.v1", "delivery", EvidenceScopeRepo, standardColumns + ` SELECT concat('acr:v1:incident:', i.id) evidence_ref_id, 'dev_health' system, 'incident' entity_type, i.id entity_id, i.title display_label, ifNull(i.source_url, '') safe_uri, ` + incidentRelationshipProvenanceMapping + ` provenance, greatest(0, least(1, coalesce(m.relationship_confidence, i.relationship_confidence, 1.0))) confidence, concat('status=', ifNull(i.normalized_status, ifNull(i.raw_status, '')), ', severity=', ifNull(i.normalized_severity, ifNull(i.raw_severity, ''))) citation, coalesce(i.started_at, i.source_event_at, i.observed_at) observed_at FROM operational_incidents AS i FINAL INNER JOIN operational_service_repository_mappings AS m FINAL ON i.org_id = m.org_id AND i.service_id = m.service_id WHERE i.org_id = {org_id:String} AND m.org_id = {org_id:String} AND m.repo_id = {repo_id:UUID} AND m.is_active = 1 AND m.valid_from <= coalesce({as_of:Nullable(DateTime64(3, 'UTC'))}, now64(6)) AND (m.valid_to IS NULL OR m.valid_to > coalesce({as_of:Nullable(DateTime64(3, 'UTC'))}, now64(6))) AND i.is_deleted = 0 AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR coalesce(i.started_at, i.source_event_at, i.observed_at) <= {as_of:Nullable(DateTime64(3, 'UTC'))}) AND ({time_window_days:UInt16} = 0 OR coalesce(i.started_at, i.source_event_at, i.observed_at) >= coalesce({as_of:Nullable(DateTime64(3, 'UTC'))}, now64(3)) - toIntervalDay({time_window_days:UInt16})) ORDER BY m.repo_id, i.id, m.relationship_confidence DESC, i.last_synced DESC, m.id ASC LIMIT 1 BY m.repo_id, i.id )`},
	{"deployment_incident_provenance.v1", "work_graph", EvidenceScopeRepo, standardColumns + ` SELECT concat('acr:v1:deployment-incident:', edge_id) evidence_ref_id, 'dev_health' system, 'deployment_incident_edge' entity_type, edge_id entity_id, concat(deployment_id, ' linked to ', incident_id) display_label, '' safe_uri, ` + deploymentIncidentProvenanceMapping + ` provenance, confidence, evidence citation, observed_at FROM work_graph_deployment_incident_edges FINAL WHERE toString(org_id) = {org_id:String} AND repo_id = {repo_id:UUID} AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR observed_at <= {as_of:Nullable(DateTime64(3, 'UTC'))}) )`},
	{"file_hotspots.v1", "code_metrics", EvidenceScopeRepo, standardColumns + ` SELECT concat('acr:v1:hotspot:', file_path) evidence_ref_id, 'dev_health' system, 'file_hotspot' entity_type, file_path entity_id, file_path display_label, '' safe_uri, 'native' provenance, least(argMax(risk_score, day) / 100.0, 1.0) confidence, concat('churn=', toString(argMax(churn_loc_30d, day)), ', complexity=', toString(argMax(cyclomatic_total, day))) citation, toDateTime(max(day)) observed_at FROM file_hotspot_daily WHERE org_id = {org_id:String} AND repo_id = {repo_id:UUID} AND (empty({files:Array(String)}) OR has({files:Array(String)}, file_path)) AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR toDateTime(day) <= {as_of:Nullable(DateTime64(3, 'UTC'))}) GROUP BY file_path )`},
	{"file_complexity.v1", "code_metrics", EvidenceScopeBranch, standardColumns + ` SELECT concat('acr:v1:complexity:', file_path) evidence_ref_id, 'dev_health' system, 'file_complexity' entity_type, file_path entity_id, file_path display_label, '' safe_uri, 'native' provenance, 1.0 confidence, concat('complexity=', toString(argMax(cyclomatic_total, as_of_day))) citation, toDateTime(max(as_of_day)) observed_at FROM file_complexity_snapshots WHERE org_id = {org_id:String} AND repo_id = {repo_id:UUID} AND ({branch:String} = '' OR ref = {branch:String}) AND (empty({files:Array(String)}) OR has({files:Array(String)}, file_path)) AND ({as_of:Nullable(DateTime64(3, 'UTC'))} IS NULL OR toDateTime(as_of_day) <= {as_of:Nullable(DateTime64(3, 'UTC'))}) GROUP BY file_path )`},
}
