apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acr-staging
resources:
  - ../../base
  - httproute.yaml
images:
  - name: acr-api
    newName: registry.internal/dev-health/acr-api
    digest: sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
patches:
  - path: config.yaml
  - path: scaling.yaml
