package contextfabric

// The obligation -> FactKind seed, GENERATED by inverting the registry's
// own declarations. Design §13.15.2 (the FactKinds SEED evidence
// obligation), §13.11a O9.
//
// THE RULE THIS FILE EXISTS TO OBEY. Law L10: no derivation rule that
// reads the fact registry is written down before it has been executed
// against the real registry, red first. The execution is
// requirement_trace_baseline_test.go; what it found is that the frozen
// hand-written seed derives 22 empty requirement cells over the four
// acceptance questions and the composed cases, 17 of them because the
// seeded kind does not serve the subject kind at all. A seed chosen from
// obligation NAMES cannot be repaired cell by cell -- `state -> status` is
// not a near-miss, it is a mapping to a producer that answers for
// work_item and nothing else.
//
// SO THE SEED IS NEVER WRITTEN. It is generated here by inverting
// FactCapability.Obligations, and the generated snapshot is checked in as
// a review surface with a test that regenerates and diffs it. The
// difference matters: a hand-written table is wrong whenever a producer
// changes and nothing notices; a generated one is wrong only where a
// declaration is wrong, and a declaration sits next to the query backing
// it where a reviewer can judge it.

import (
	"fmt"
	"sort"
	"strings"
)

// obligationRequiredTableShape is the closed set of obligations that can
// only be served by a DECLARED TABLE of a particular shape, and it is a
// property of the obligation rather than of any producer.
//
// A trend is not a scalar read taken four times: serving `trend_series`
// means emitting a time_series table, and a producer that answers a team
// with a scalar cannot serve it however relevant its dimension is. The
// same holds for `allocation_breakdown`, whose whole content is the
// breakdown -- an investment scalar is a number with no allocation in it.
//
// Every other read obligation is satisfiable by a scalar read, so it has
// no entry here and the seed admits any declaring producer that supports
// the subject kind.
//
// THIS IS THE ONE PLACE THE SHAPE CLAUSE LIVES. The frozen design spread a
// required-shape column across a per-obligation table that also carried
// seeds, quantifiers and renders, and the executed trace could not tell
// which column emptied a cell. Keeping the shape rule alone and closed is
// what lets the trace attribute an empty cell to a subject-kind miss, a
// dimension miss or a shape miss and report which.
var obligationRequiredTableShape = map[AnswerObligation]FactTableShape{
	ObligationTrendSeries:         FactTableTimeSeries,
	ObligationAllocationBreakdown: FactTableBreakdown,
}

// RequiredTableShapeFor reports the table shape an obligation demands, and
// whether it demands one at all.
func RequiredTableShapeFor(obligation AnswerObligation) (FactTableShape, bool) {
	shape, required := obligationRequiredTableShape[obligation]
	return shape, required
}

// ObligationSeed maps a read obligation and a subject kind to the fact
// kinds that can serve it. A missing or empty entry is meaningful: no
// producer serves that obligation for that subject kind, which the
// requirement layer renders as an explicit `unavailable` rather than as a
// silent empty set.
type ObligationSeed map[AnswerObligation]map[SubjectKind][]FactKind

// GenerateObligationSeed inverts the registry's declarations.
//
// A (obligation, subjectKind) cell contains every fact kind whose
// capability (a) declares that obligation FOR that subject kind, and (b)
// where the obligation demands a table shape, declares that shape for that
// same subject kind -- never a global table list, because a capability can
// emit a time_series for a repository and a scalar for a team
// (metrics.go is exactly that).
//
// Both clauses are keyed on the subject kind, and that is the measured
// shape rather than a symmetry for its own sake: see
// FactCapability.Obligations for the three cells a subject-kind-blind
// declaration got wrong against the CHAOS-4347 composition.
//
// It is pure and total over its input. It reads no global state, so the
// generated artifact is a function of the registry alone and a diff in the
// artifact is always attributable to a declaration change.
func GenerateObligationSeed(capabilities []FactCapability) ObligationSeed {
	// Deduplicated by construction, and this is a correctness requirement
	// rather than tidiness. Cardinality() counts what lands in these
	// slices and Cardinality SETS THE COMPLETION QUANTIFIER (law L3), so a
	// fact kind appearing twice in one cell would report two independent
	// producers where there is one and demand corroboration that cannot
	// exist. Round 1 found the unguarded version: two capabilities sharing
	// a Kind produced `[health health]` with Cardinality 2, and every
	// oracle stayed green because Render() and the parity property both
	// compare SETS. The generator is the only place that can prevent it --
	// FactCapability.Validate rejects a duplicate WITHIN one declaration
	// but says nothing about two capabilities, and this function is
	// exported and takes a raw slice.
	seen := map[AnswerObligation]map[SubjectKind]map[FactKind]bool{}
	seed := ObligationSeed{}
	for _, capability := range capabilities {
		for subject, obligations := range capability.Obligations {
			for _, obligation := range obligations {
				if shape, required := obligationRequiredTableShape[obligation]; required && !capabilityDeclaresShape(capability, subject, shape) {
					continue
				}
				bySubject, known := seed[obligation]
				if !known {
					bySubject = map[SubjectKind][]FactKind{}
					seed[obligation] = bySubject
					seen[obligation] = map[SubjectKind]map[FactKind]bool{}
				}
				if seen[obligation][subject] == nil {
					seen[obligation][subject] = map[FactKind]bool{}
				}
				if seen[obligation][subject][capability.Kind] {
					continue
				}
				seen[obligation][subject][capability.Kind] = true
				bySubject[subject] = append(bySubject[subject], capability.Kind)
			}
		}
	}
	for _, bySubject := range seed {
		for subject, kinds := range bySubject {
			sort.Slice(kinds, func(i, j int) bool { return kinds[i] < kinds[j] })
			bySubject[subject] = kinds
		}
	}
	return seed
}

func capabilityDeclaresShape(capability FactCapability, subject SubjectKind, shape FactTableShape) bool {
	for _, declared := range capability.Tables[subject] {
		if declared == shape {
			return true
		}
	}
	return false
}

// KindsFor returns the fact kinds serving one cell, or nil when none do.
// The returned slice is a copy: a caller that sorts or appends cannot
// corrupt the seed for every later caller.
func (s ObligationSeed) KindsFor(obligation AnswerObligation, subject SubjectKind) []FactKind {
	kinds := s[obligation][subject]
	if len(kinds) == 0 {
		return nil
	}
	return append([]FactKind(nil), kinds...)
}

// Cardinality is how many distinct fact kinds serve a cell.
//
// THIS IS WHAT SETS THE COMPLETION QUANTIFIER (law L3, §13.15.2). The
// frozen design fixed `state = corroborated` as a constant, and §13.15.2
// records why that could not stand: corroboration cannot be met by a
// one-kind seed, and the escape clause ("or the registry declares only one
// kind") silently degraded it to at_least_one wherever it bit. Deriving
// the quantifier from the measured cardinality instead means the plan
// demands corroboration exactly where corroboration is available, and says
// so where it is not, rather than asserting a bar it then quietly lowers.
func (s ObligationSeed) Cardinality(obligation AnswerObligation, subject SubjectKind) int {
	return len(s[obligation][subject])
}

// ServedSubjectKinds lists the subject kinds an obligation has any
// producer for, in vocabulary-stable (sorted) order.
func (s ObligationSeed) ServedSubjectKinds(obligation AnswerObligation) []SubjectKind {
	bySubject := s[obligation]
	subjects := make([]SubjectKind, 0, len(bySubject))
	for subject, kinds := range bySubject {
		if len(kinds) > 0 {
			subjects = append(subjects, subject)
		}
	}
	sort.Slice(subjects, func(i, j int) bool { return subjects[i] < subjects[j] })
	return subjects
}

// Render writes the seed as a stable, human-readable snapshot.
//
// It is the checked-in artifact's format, and it is deliberately a text
// table rather than JSON: the artifact's whole job is to make a
// declaration change legible in a review diff, and a reviewer reads
// "state  team  flow health investment landscape readiness workload" far
// faster than the same thing in braces. Determinism is what makes the diff
// trustworthy, so every level is sorted.
func (s ObligationSeed) Render() string {
	obligations := make([]string, 0, len(s))
	for obligation := range s {
		obligations = append(obligations, string(obligation))
	}
	sort.Strings(obligations)

	var out strings.Builder
	out.WriteString("# GENERATED by GenerateObligationSeed from the fact registry's own\n")
	out.WriteString("# FactCapability.Obligations declarations. DO NOT EDIT BY HAND: a test\n")
	out.WriteString("# regenerates this file and fails on any difference, so a hand edit is\n")
	out.WriteString("# reverted by the next run rather than silently becoming the seed.\n")
	out.WriteString("#\n")
	out.WriteString("# obligation / subject kind / fact kinds that can serve the cell.\n")
	out.WriteString("# A subject kind absent from an obligation's block has NO producer for\n")
	out.WriteString("# it -- the requirement layer renders that as an explicit `unavailable`,\n")
	out.WriteString("# never as a silent empty set.\n")
	for _, name := range obligations {
		obligation := AnswerObligation(name)
		out.WriteString("\n" + name + "\n")
		for _, subject := range s.ServedSubjectKinds(obligation) {
			kinds := s.KindsFor(obligation, subject)
			rendered := make([]string, 0, len(kinds))
			for _, kind := range kinds {
				rendered = append(rendered, string(kind))
			}
			fmt.Fprintf(&out, "  %-20s %s\n", subject, strings.Join(rendered, " "))
		}
	}
	return out.String()
}
