package contextfabric_test

// ORACLE O9 -- the S7b-ii entry gate, rebuilt on the PRODUCTION derivation.
// Design §13.11a (O9), §13.15.1 (the executed trace that forced the
// excision), §13.15.2 (the per-rule evidence obligations), law L10.
//
// WHAT CHANGED SINCE THE DECLARATION SLICE, AND WHY IT MATTERS. That slice
// carried a hand-written coordinate table inside a test file and shipped a
// PINNED empty-cell count. Three adversarial rounds each found a hole in
// the code written to close the previous round's finding, and the
// scaffolding was removed rather than approximated a fourth time. The root
// cause was structural: the coordinates, the artifact that displayed them
// and the assertion that checked them were three views of ONE table living
// in ONE file, so a coordinated edit moved all three and every test stayed
// green.
//
// Here there is no table. The coordinates come from
// contextfabric.DeriveRequirementCoordinates and the rows from
// contextfabric.DeriveRequirements -- PRODUCTION functions -- run against
// devhealthfacts.NewProviders, the live registry. The artifact is their
// OUTPUT: it is regenerated by calling them and diffed, so there is nothing
// for an edit to be coordinated across. The unserved/derived pair is a
// number IN THE ARTIFACT, not a constant in this file, which is what makes
// it a measurement rather than something a reviewer can tune to match.
//
// WHAT O9 ASSERTS, in the ticket's own words: "every required READ
// obligation cell either names >=1 fact kind a producer can serve for that
// subject kind, or names `unavailable` with a closed reason token -- never
// silently empty; every COMPUTED obligation names its server step
// (RankCohort for ranking, a cardinality for count); and `state`@team and
// `state`@project equal statusCategoryFactKindComposition by set equality
// in both directions". All three are asserted below. Note what that
// condition IS and IS NOT: it is not "every cell is served" -- the registry
// genuinely cannot serve some of them, and pretending otherwise is what the
// frozen seed did. It is that no cell is silently empty. The count of cells
// the registry cannot serve is REPORTED, with its causes, in the artifact.
//
// IT LIVES IN THE EXTERNAL TEST PACKAGE because devhealthfacts imports
// contextfabric, so an in-package file cannot import it back. Running
// against a hand-built fixture registry instead would test the fixture, not
// the registry the engine actually plans against -- and that is the whole
// point of the gate. (Rule-level tests against a constructed registry do
// exist, in requirement_derivation_test.go, for the opposite reason: those
// pin rules that must NOT move when a declaration does.)
//
// CORPUS SAFETY. Frames are identified by QUESTION ID and by a STRUCTURAL
// label (topology + operation) only. No corpus question text appears in
// this file, in its output, or in the artifact. The frames are built
// THROUGH the shipped frame layer (DeriveFrameObligations), never by
// hand-typing an obligation list, so a change to §13.2.3's tables moves
// this trace with it rather than leaving it silently disagreeing.
//
// HOST-ONLY. The registry reader this file uses (liveCapabilityList, in
// obligation_seed_test.go) reads Capability() declarations and never
// constructs a provider client, so nothing here starts a container. The
// devhealthfacts PACKAGE's own tests do start ClickHouse; they are not run
// by this file's command.

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/full-chaos/dev-health-acr/internal/contextfabric"
)

const requirementTraceArtifact = "testdata/requirement_trace.txt"

// traceFrame is one frame of the executed trace.
type traceFrame struct {
	// id is the question ID. NEVER the question text.
	id string
	// shape is a STRUCTURAL label -- topology plus operation -- not a
	// paraphrase: it names the frame, not the question.
	shape string
	frame contextfabric.QuestionFrame
	// recorded marks the thirteen frames of the trace ON RECORD. C2s is
	// the one addition (see traceExplicitMixed) and is false, so the
	// artifact can report a subtotal that stays comparable to the
	// measurement of record.
	recorded bool
}

func traceKindPointer(kind contextfabric.SubjectKind) *contextfabric.SubjectKind {
	return &kind
}

func traceBuildFrame(
	goals []contextfabric.InvestigationGoal,
	expression contextfabric.SubjectExpression,
	temporal contextfabric.TemporalIntent,
	emphasis []contextfabric.AnswerEmphasis,
	dimensions []contextfabric.HealthDimension,
) contextfabric.QuestionFrame {
	return contextfabric.DeriveFrameObligations(contextfabric.QuestionFrame{
		Goals:             goals,
		SubjectExpression: expression,
		Temporal:          temporal,
		Emphasis:          emphasis,
		Dimensions:        dimensions,
		Version:           contextfabric.QuestionFrameVersion,
	}, nil)
}

func traceNamed(kind contextfabric.SubjectKind) contextfabric.SubjectExpression {
	return contextfabric.SubjectExpression{
		Kind:  contextfabric.SubjectExpressionNamed,
		Named: &contextfabric.NamedSubjectExpression{Terms: []string{"s"}, ExpectedKind: traceKindPointer(kind)},
	}
}

func traceDiscovered(member contextfabric.SubjectKind) contextfabric.SubjectExpression {
	return contextfabric.SubjectExpression{
		Kind:       contextfabric.SubjectExpressionDiscoveredKind,
		Discovered: &contextfabric.DiscoveredSetExpression{MemberKind: member},
	}
}

func traceGrouped(group, member contextfabric.SubjectKind) contextfabric.SubjectExpression {
	return contextfabric.SubjectExpression{
		Kind:    contextfabric.SubjectExpressionGroupedMembers,
		Grouped: &contextfabric.GroupedSetExpression{GroupKind: group, MemberKind: member},
	}
}

func traceScoped(member contextfabric.SubjectKind) contextfabric.SubjectExpression {
	return contextfabric.SubjectExpression{
		Kind:   contextfabric.SubjectExpressionChildrenOfScope,
		Scoped: &contextfabric.ScopedSetExpression{AnchorTerms: []string{"a"}, MemberKind: member},
	}
}

// traceExplicit builds the comparison used by C2 and C6, FAITHFUL to the
// recorded corpus: two NAMED operands of the same kind.
//
// It is kept exactly as the recorded trace had it so that this gate's
// measurement stays directly comparable to the one on record. Changing the
// corpus and the derivation in the same change would make any movement in
// the numbers unattributable.
func traceExplicit(kind contextfabric.SubjectKind) contextfabric.SubjectExpression {
	operand := func(term string) contextfabric.SubjectOperand {
		return contextfabric.SubjectOperand{
			Kind:  contextfabric.SubjectOperandNamed,
			Named: &contextfabric.NamedSubjectExpression{Terms: []string{term}, ExpectedKind: traceKindPointer(kind)},
		}
	}
	return contextfabric.SubjectExpression{
		Kind:     contextfabric.SubjectExpressionExplicitSet,
		Explicit: &contextfabric.ExplicitSetExpression{Operands: []contextfabric.SubjectOperand{operand("a"), operand("b")}},
	}
}

// traceExplicitMixed is C2s, the ONE frame ADDED to the recorded corpus,
// and it is added for a reason the record itself supplies.
//
// Every explicit set in the thirteen recorded frames has two NAMED operands.
// SubjectOperand is a union of named AND scoped (invariant I19), and round 3
// of the declaration slice found the coordinate derivation reading the named
// arm only -- a scoped operand's cells vanished and every test stayed green,
// precisely because no frame in the corpus had one. A corpus that cannot
// exhibit a defect cannot gate against it.
//
// It is a SEPARATE frame rather than a change to C2 so that the thirteen
// recorded frames keep their recorded shape: the artifact reports the
// thirteen-frame subtotal alongside the total, so the measurement of record
// stays comparable and this addition is visible rather than folded in.
func traceExplicitMixed() contextfabric.SubjectExpression {
	return contextfabric.SubjectExpression{
		Kind: contextfabric.SubjectExpressionExplicitSet,
		Explicit: &contextfabric.ExplicitSetExpression{Operands: []contextfabric.SubjectOperand{
			{Kind: contextfabric.SubjectOperandNamed, Named: &contextfabric.NamedSubjectExpression{Terms: []string{"a"}, ExpectedKind: traceKindPointer(contextfabric.SubjectTeam)}},
			{Kind: contextfabric.SubjectOperandScoped, Scoped: &contextfabric.ScopedSetExpression{AnchorTerms: []string{"b"}, MemberKind: contextfabric.SubjectProject}},
		}},
	}
}

func traceOrg(member *contextfabric.SubjectKind) contextfabric.SubjectExpression {
	return contextfabric.SubjectExpression{
		Kind: contextfabric.SubjectExpressionOrganizationScope,
		Org:  &contextfabric.OrganizationScopeExpression{MemberKind: member},
	}
}

// traceFrames is the corpus: the acceptance questions Q1, Q1', Q2, Q-A and
// Q-B, the composed cases C1-C7, and B5. Thirteen frames, question ids
// only.
func traceFrames() []traceFrame {
	repository := contextfabric.SubjectRepository
	return []traceFrame{
		{"Q1", "named subject (team), assess_state",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalAssessState}, traceNamed(contextfabric.SubjectTeam), contextfabric.TemporalIntentCurrent, nil, nil), true},
		{"Q1'", "named subject (project), assess_state",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalAssessState}, traceNamed(contextfabric.SubjectProject), contextfabric.TemporalIntentCurrent, nil, nil), true},
		{"Q2", "discovered team, rank + explain",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalRankOrSurvey, contextfabric.GoalExplainDrivers}, traceDiscovered(contextfabric.SubjectTeam), contextfabric.TemporalIntentCurrent, nil, nil), true},
		{"Q-A", "grouped team->project, assess + explain",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalAssessState, contextfabric.GoalExplainDrivers}, traceGrouped(contextfabric.SubjectTeam, contextfabric.SubjectProject), contextfabric.TemporalIntentCurrent, nil, nil), true},
		{"Q-B", "scoped team->project, assess",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalAssessState}, traceScoped(contextfabric.SubjectProject), contextfabric.TemporalIntentCurrent, nil, nil), true},
		{"C1", "grouped team->project, assess + trend, time_series",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalAssessState, contextfabric.GoalDescribeTrend}, traceGrouped(contextfabric.SubjectTeam, contextfabric.SubjectProject), contextfabric.TemporalIntentTimeSeries, nil, nil), true},
		{"C2", "explicit_set two named team operands, compare, dims=investment_balance",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalCompare}, traceExplicit(contextfabric.SubjectTeam), contextfabric.TemporalIntentCurrent, nil, []contextfabric.HealthDimension{contextfabric.HealthDimensionInvestmentBalance}), true},
		{"C3", "grouped team->project, explain_change, period_comparison, dims=delivery_flow",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalExplainChange}, traceGrouped(contextfabric.SubjectTeam, contextfabric.SubjectProject), contextfabric.TemporalIntentPeriodComparison, nil, []contextfabric.HealthDimension{contextfabric.HealthDimensionDeliveryFlow}), true},
		{"C4", "discovered team, rank, both-ends emphasis",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalRankOrSurvey}, traceDiscovered(contextfabric.SubjectTeam), contextfabric.TemporalIntentCurrent, []contextfabric.AnswerEmphasis{contextfabric.EmphasisPositiveOutliers, contextfabric.EmphasisNegativeOutliers}, nil), true},
		{"C5", "scoped repository->team, count",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalCountOrAggregate}, traceScoped(contextfabric.SubjectTeam), contextfabric.TemporalIntentCurrent, nil, nil), true},
		{"C6", "explicit_set two named team operands, compare + trend, time_series, dims=investment_balance",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalCompare, contextfabric.GoalDescribeTrend}, traceExplicit(contextfabric.SubjectTeam), contextfabric.TemporalIntentTimeSeries, nil, []contextfabric.HealthDimension{contextfabric.HealthDimensionInvestmentBalance}), true},
		{"C7", "organization scope, count, MemberKind=repository",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalCountOrAggregate}, traceOrg(&repository), contextfabric.TemporalIntentCurrent, nil, nil), true},
		{"B5", "organization scope, assess_state",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalAssessState}, traceOrg(nil), contextfabric.TemporalIntentCurrent, nil, nil), true},
		// ADDED to the recorded thirteen -- see traceExplicitMixed.
		{"C2s", "explicit_set (named team operand, SCOPED project operand), compare",
			traceBuildFrame([]contextfabric.InvestigationGoal{contextfabric.GoalCompare}, traceExplicitMixed(), contextfabric.TemporalIntentCurrent, nil, nil), false},
	}
}

// The live registry's declarations come from liveCapabilityList, declared
// in obligation_seed_test.go and REUSED here rather than re-read, so "the
// live registry" has exactly ONE definition in this package's external test
// binary. Two readers of the same registry that could disagree is the shape
// of defect this slice's whole review history is about. It reads
// Capability() declarations only and constructs no provider client, so
// nothing in this file touches ClickHouse or starts a container.

// recordedFrameCount is how many of the corpus frames are the trace ON
// RECORD. Derived from the corpus rather than written down, so adding a
// frame cannot leave a stale constant behind.
func recordedFrameCount() int {
	count := 0
	for _, testCase := range traceFrames() {
		if testCase.recorded {
			count++
		}
	}
	return count
}

// TestEveryRequirementCellIsServedOrNamesAClosedReason is oracle O9's own
// assertion: never silently empty.
//
// This is the condition the entry gate was written to reach, and reaching
// it is what replaces the declaration slice's pinned baseline. It does NOT
// say the registry can serve everything -- it says that where it cannot,
// the derivation SAYS SO, with a token from a closed vocabulary that names
// what would have to change.
func TestEveryRequirementCellIsServedOrNamesAClosedReason(t *testing.T) {
	capabilities := liveCapabilityList(t)
	seed := contextfabric.GenerateObligationSeed(capabilities)

	validReasons := map[contextfabric.RequirementUnavailableReason]bool{}
	for _, reason := range contextfabric.RequirementUnavailableReasonVocabulary() {
		validReasons[reason] = true
	}

	cells := 0
	framesWithRows := 0
	for _, testCase := range traceFrames() {
		rows := contextfabric.DeriveRequirements(testCase.frame, seed, capabilities)
		if len(rows) == 0 {
			t.Errorf("%s (%s): derived no requirement rows at all", testCase.id, testCase.shape)
			continue
		}
		framesWithRows++
		if err := contextfabric.RequirementRowsAreWellFormed(rows); err != nil {
			t.Errorf("%s (%s): %v", testCase.id, testCase.shape, err)
		}
		for _, row := range rows {
			if row.Served() {
				switch row.Kind {
				case contextfabric.ObligationKindComputed:
					if row.Step == "" {
						t.Errorf("%s: computed %s@%s names no server step", testCase.id, row.Obligation, row.Subject)
					}
				default:
					if len(row.FactKinds) == 0 {
						t.Errorf("%s: served read %s@%s names no fact kind", testCase.id, row.Obligation, row.Subject)
					}
				}
			} else if !validReasons[row.Unavailable] {
				t.Errorf("%s: %s@%s is unavailable for out-of-vocabulary reason %q", testCase.id, row.Obligation, row.Subject, row.Unavailable)
			}
			cells++
		}
	}
	if framesWithRows != len(traceFrames()) {
		t.Errorf("%d of %d frames produced rows", framesWithRows, len(traceFrames()))
	}
	if cells == 0 {
		t.Fatal("no requirement cells reached the assertions -- the gate proved nothing")
	}
	t.Logf("O9: %d requirement cells derived across %d frames, all served or named", cells, framesWithRows)
}

// TestEveryComputedObligationNamesItsServerStep is O9's second clause,
// asserted over the live corpus rather than over the fixture.
//
// The frozen table modelled `ranking` as a READ with a required table shape
// no producer declares, so BAR question Q2's DEFINING obligation was
// unavailable by construction (round 4, N3). That mis-typing is what this
// clause exists to keep out.
func TestEveryComputedObligationNamesItsServerStep(t *testing.T) {
	capabilities := liveCapabilityList(t)
	seed := contextfabric.GenerateObligationSeed(capabilities)

	computed, servedComputed, unavailableComputed := 0, 0, 0
	for _, testCase := range traceFrames() {
		for _, row := range contextfabric.DeriveRequirements(testCase.frame, seed, capabilities) {
			if row.Kind != contextfabric.ObligationKindComputed {
				continue
			}
			computed++
			want, named := contextfabric.StepForComputedObligation(row.Obligation)
			if !named {
				t.Errorf("%s: %s is classified computed but names no step in the vocabulary", testCase.id, row.Obligation)
				continue
			}
			// A COMPUTED CELL EITHER NAMES ITS STEP OR NAMES A CLOSED REASON
			// IT CANNOT RUN -- exactly the disjunction the READ clause above
			// has always had, and never a silent third state.
			//
			// The clause used to demand a step unconditionally. An
			// adversarial round showed that is too strong: an
			// organization-scope frame names a member kind, so the coordinate
			// is legitimate, but nothing discovers that population -- the
			// step has no input and the cell cannot be served. Demanding a
			// step there forced the row to CLAIM a server for work nothing
			// could do, which is the same over-claim the execution
			// declaration was added to stop, one level in. Naming the reason
			// is strictly more than naming an unrunnable step.
			if !row.Served() {
				if row.Unavailable == "" {
					t.Errorf("%s: computed %s@%s is unserved and names no reason -- the silent emptiness this gate exists to forbid",
						testCase.id, row.Obligation, row.Subject)
				}
				if row.Step != "" {
					t.Errorf("%s: computed %s@%s names BOTH a step and a reason it cannot run -- two answers to what became of the cell",
						testCase.id, row.Obligation, row.Subject)
				}
				unavailableComputed++
				continue
			}
			if row.Step != want {
				t.Errorf("%s: %s@%s names step %q, want %q", testCase.id, row.Obligation, row.Subject, row.Step, want)
			}
			servedComputed++
		}
	}
	if computed == 0 {
		t.Fatal("no computed obligation reached the assertions; Q2, C4, C5 and C7 all derive one, so the corpus or the derivation is wrong")
	}
	// BOTH sides of the disjunction must be populated, or the clause is
	// one-sided: all-served would make the unavailable arm dead, and
	// all-unavailable would mean no frame in the corpus can run a
	// computation at all.
	if servedComputed == 0 || unavailableComputed == 0 {
		t.Fatalf("computed cells are one-sided: %d served, %d unavailable -- one arm of this clause is untested",
			servedComputed, unavailableComputed)
	}
	t.Logf("O9: %d computed requirement cells -- %d name their server step, %d name a closed reason they cannot run",
		computed, servedComputed, unavailableComputed)
}

// TestStateCompositionParityAgainstTheLiveRegistry is the N2 parity
// property: the generated seed's `state` set for team and project equals
// the CHAOS-4347 status composition, by SET EQUALITY IN BOTH DIRECTIONS.
//
// Both directions matter and one direction would have missed the defect
// that produced the shipped declaration shape: a flat obligation list
// diverged only by an EXTRA kind, never a missing one, so a subset check
// would have passed while the plan read facts the composition excludes.
func TestStateCompositionParityAgainstTheLiveRegistry(t *testing.T) {
	capabilities := liveCapabilityList(t)
	seed := contextfabric.GenerateObligationSeed(capabilities)
	composition := contextfabric.StatusCategoryCompositionForTest()

	checked := 0
	for _, subject := range []contextfabric.SubjectKind{contextfabric.SubjectTeam, contextfabric.SubjectProject} {
		want, declared := composition[subject]
		if !declared || len(want) == 0 {
			t.Fatalf("the composition has no row for %q, so this comparison has no reference", subject)
		}
		got := seed.KindsFor(contextfabric.ObligationState, subject)
		if diff := setDifference(got, want); len(diff) > 0 {
			t.Errorf("state@%s: the seed serves %v, which the composition excludes", subject, diff)
		}
		if diff := setDifference(want, got); len(diff) > 0 {
			t.Errorf("state@%s: the composition names %v, which the seed does not serve", subject, diff)
		}
		checked++
	}
	if checked != 2 {
		t.Fatalf("compared %d composition rows, want 2", checked)
	}
}

func setDifference(from, minus []contextfabric.FactKind) []contextfabric.FactKind {
	remove := make(map[contextfabric.FactKind]bool, len(minus))
	for _, kind := range minus {
		remove[kind] = true
	}
	var diff []contextfabric.FactKind
	for _, kind := range from {
		if !remove[kind] {
			diff = append(diff, kind)
		}
	}
	sort.Slice(diff, func(i, j int) bool { return diff[i] < diff[j] })
	return diff
}

// TestRequirementTraceArtifactIsRegenerated is the ROT GUARD -- the one the
// derivation gets, per the slice's own bar.
//
// The artifact is an OUTPUT. It is produced by calling the production
// renderers over the live registry and compared byte for byte with the
// checked-in file. There is no second table it is rendered from and no
// constant in this file it is compared against, which is the property the
// declaration slice's artifact lacked through two review rounds: there, the
// renderer walked a hand table, so deleting a cell removed it from the
// artifact AND from the assertion and everything stayed green.
//
// THE MEASUREMENT LIVES IN THE ARTIFACT, NOT IN GO SOURCE. The derived and
// unserved cell counts and the cause distribution are lines of the
// generated file. A registry change moves them and the diff is the review
// surface; there is deliberately no constant here to edit into agreement.
// A count that moves is a MEASUREMENT to be explained -- and the causes at
// the foot are what explain it, since the total can stay put while its
// composition changes (a producer gaining a subject kind while another
// loses one nets to zero).
func TestRequirementTraceArtifactIsRegenerated(t *testing.T) {
	generated := renderRequirementTrace(t)

	recorded, err := os.ReadFile(requirementTraceArtifact)
	if err != nil {
		t.Fatalf("reading %s: %v\n\nthe generated content is:\n\n%s", requirementTraceArtifact, err, generated)
	}
	if string(recorded) != generated {
		t.Fatalf("%s is stale. Regenerate it and read the cause distribution at the foot: "+
			"the total can stay put while its composition moves, so the causes are what say what changed.\n\n--- generated ---\n%s", requirementTraceArtifact, generated)
	}
}

// renderRequirementTrace produces the artifact's whole content from the
// production functions and the live registry.
func renderRequirementTrace(t *testing.T) string {
	t.Helper()
	capabilities := liveCapabilityList(t)
	seed := contextfabric.GenerateObligationSeed(capabilities)

	var out strings.Builder
	out.WriteString("# GENERATED by TestRequirementTraceArtifactIsRegenerated from the PRODUCTION\n")
	out.WriteString("# derivation (DeriveRequirementCoordinates + DeriveRequirements) run against\n")
	out.WriteString("# the live fact registry. DO NOT EDIT BY HAND: the test regenerates this file\n")
	out.WriteString("# and fails on any difference.\n")
	out.WriteString("#\n")
	out.WriteString("# Oracle O9, design 13.11a. Thirteen frames: the acceptance questions Q1, Q1',\n")
	out.WriteString("# Q2, Q-A and Q-B, the composed cases C1-C7, and B5. QUESTION IDS ONLY -- no\n")
	out.WriteString("# corpus text appears here or in the code that renders it.\n")
	out.WriteString("#\n")
	out.WriteString("# Columns: obligation / role / subject kind / completion scope / quantifier /\n")
	out.WriteString("# server. A server reads `UNAVAILABLE <reason>` where no producer can serve the\n")
	out.WriteString("# cell -- never a silent blank, which is the condition O9 asserts.\n")
	out.WriteString("#\n")
	out.WriteString("# THE ANCHOR ROLE HAS NO ROW ANYWHERE, by design. ScopedSetExpression's\n")
	out.WriteString("# AnchorTerms are retrieval pointers, never values, so an anchor's subject kind\n")
	out.WriteString("# is settled at resolution time and the frame -- immutable before resolution --\n")
	out.WriteString("# cannot name it. The absence is a measured bound, not an omission.\n")

	var all, recorded []contextfabric.DerivedRequirement
	for _, testCase := range traceFrames() {
		rows := contextfabric.DeriveRequirements(testCase.frame, seed, capabilities)
		all = append(all, rows...)
		if testCase.recorded {
			recorded = append(recorded, rows...)
		}
		marker := ""
		if !testCase.recorded {
			marker = "  (ADDED to the recorded thirteen)"
		}
		out.WriteString("\n")
		out.WriteString(contextfabric.RenderRequirements(testCase.id+"  ["+testCase.shape+"]"+marker, rows))
	}

	out.WriteString("\n")
	writeMeasurement(&out, "MEASUREMENT (recorded thirteen frames)", recorded, recordedFrameCount())
	writeMeasurement(&out, "MEASUREMENT (whole corpus)", all, len(traceFrames()))
	out.WriteString("#\n")
	out.WriteString(contextfabric.RenderRequirementCauseDistribution(contextfabric.RequirementCauseDistribution(all)))
	return out.String()
}

// writeMeasurement reports one cell tally.
//
// THE RECORDED-THIRTEEN SUBTOTAL IS REPORTED SEPARATELY so that this gate's
// number stays directly comparable to the measurement on record, which was
// taken over those thirteen frames. Folding the added frame into a single
// total would move the number for a reason that has nothing to do with the
// derivation, and an unattributable movement is exactly what a measurement
// must not have.
func writeMeasurement(out *strings.Builder, label string, rows []contextfabric.DerivedRequirement, frames int) {
	served, unserved := 0, 0
	for _, row := range rows {
		if row.Served() {
			served++
		} else {
			unserved++
		}
	}
	fmt.Fprintf(out, "# %s: %d requirement cells derived over %d frames; %d served, %d unserved.\n",
		label, len(rows), frames, served, unserved)
}

// TestTheCorpusExercisesEveryVariantAndEveryRole is the gate's own
// non-vacuity check.
//
// A corpus that never builds a grouped frame cannot notice a broken group
// rule, and a corpus with no scoped operand is exactly the blind spot round
// 3 found. Rather than trusting the thirteen frames to be diverse, the
// coverage is asserted: every member of the subject-expression vocabulary
// and every subject role must appear.
func TestTheCorpusExercisesEveryVariantAndEveryRole(t *testing.T) {
	variants := map[contextfabric.SubjectExpressionKind]bool{}
	roles := map[contextfabric.SubjectRole]bool{}
	for _, testCase := range traceFrames() {
		variants[testCase.frame.SubjectExpression.Kind] = true
		for _, coordinate := range contextfabric.DeriveRequirementCoordinates(testCase.frame) {
			roles[coordinate.Role] = true
		}
	}
	for _, variant := range contextfabric.SubjectExpressionKindVocabulary() {
		if !variants[variant] {
			t.Errorf("no frame in the corpus uses subject expression %q, so the gate cannot see that variant's role rules", variant)
		}
	}
	for _, role := range contextfabric.SubjectRoleVocabulary() {
		if !roles[role] {
			t.Errorf("no frame in the corpus produces role %q, so the gate cannot see its completion scope or its attachment rule", role)
		}
	}
}
