package diagnostics

import (
	"fmt"
	"strings"
)

// readmeText renders the bundle's interpretation guide: what each file
// means, and an explicit statement of what this bundle never contains, so
// a recipient (a support engineer, or the operator themselves) can read it
// without cross-referencing external documentation first.
func readmeText(input Input) string {
	var b strings.Builder
	b.WriteString("# ACR MCP Diagnostic Bundle\n\n")
	fmt.Fprintf(&b, "Generated by acr-mcp %s (commit %s, built %s) on %s/%s.\n\n",
		input.Identity.Version, input.Identity.Commit, input.Identity.BuildDate,
		input.Identity.GOOS, input.Identity.GOARCH)

	b.WriteString("## Files\n\n")
	fmt.Fprintf(&b, "- `%s`: schema-versioned index of this bundle's contents.\n", manifestFile)
	fmt.Fprintf(&b, "- `%s`: the static, network-free `acr-mcp doctor --offline` report -- presence/validity flags and bounded, non-secret configuration values only.\n", staticReportFile)
	if input.Live != nil {
		fmt.Fprintf(&b, "- `%s`: the sanitized `acr-mcp doctor --live` result -- a real hosted capabilities handshake reduced to booleans and enabled-tool names.\n", liveReportFile)
	} else {
		fmt.Fprintf(&b, "- `%s` was not requested for this bundle (no live hosted-API check was performed).\n", liveReportFile)
	}
	fmt.Fprintf(&b, "- `%s`: this file.\n\n", interpretationDoc)

	b.WriteString("## Sharing this bundle\n\n")
	b.WriteString("Share this bundle only through approved private support channels. Do not attach it to public issues, even though its contents are sanitized.\n\n")

	b.WriteString("## Metadata in this bundle\n\n")
	b.WriteString("The manifest records its schema version, generation time, file list, top-level status, and whether a live report is present. Its identity fields identify the sidecar service, version, commit, build date, GOOS, and GOARCH. The static report records configuration presence and validity, credential source category, feature flags, log level, bounded configuration values, and named checks. An optional live report records sanitized reachability, entitlement and scope booleans, feature gates, and enabled tool names.\n\n")

	b.WriteString("## What this bundle does NOT contain\n\n")
	b.WriteString("This bundle is sanitized for approved private support channels. It never contains:\n\n")
	b.WriteString("- The configured `ACR_API_URL` host, or any userinfo embedded in it.\n")
	b.WriteString("- The bearer credential value, in any form.\n")
	b.WriteString("- Any filesystem path (token file, CA bundle, or otherwise).\n")
	b.WriteString("- The contents of a configured CA bundle.\n")
	b.WriteString("- Any HTTP request or response header.\n")
	b.WriteString("- Any HTTP request or response body.\n\n")

	b.WriteString("## Interpreting the status field\n\n")
	fmt.Fprintf(&b, "Top-level status: `%s`.\n\n", input.Static.Status)
	b.WriteString("- `ok`: static local configuration is present and valid.\n")
	b.WriteString("- `incomplete_configuration`: the API URL or credential is not configured at all.\n")
	b.WriteString("- `invalid_configuration`: something is configured but malformed (see the `checks` list in the static report for which one).\n")
	b.WriteString("- `credential_unavailable`: the credential source could not be checked safely, for example because another lifecycle operation holds the lock or a secure store is unavailable.\n")
	b.WriteString("- `live_check_unreachable`: the static configuration is valid, but the optional live hosted-API check in this bundle could not reach or was rejected by the hosted API.\n")

	return b.String()
}
